# Pure provider policy. Inputs are internal collector/catalog observations, never profile fields.
function Get-AcHash($Value){
 $json=ConvertTo-AcCanonical $Value
 $sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($json)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}
}
function ConvertTo-AcCanonical($Value){
 if($null -eq $Value){return 'null'}
 if($Value -is [Collections.IDictionary]){$pairs=@();foreach($key in @($Value.Keys | Sort-Object -CaseSensitive)){$pairs+=((ConvertTo-Json ([string]$key) -Compress)+':'+(ConvertTo-AcCanonical $Value[$key]))};return '{'+($pairs -join ',')+'}'}
 if($Value -is [pscustomobject]){$map=@{};foreach($p in $Value.PSObject.Properties){$map[$p.Name]=$p.Value};return ConvertTo-AcCanonical $map}
 if($Value -is [Array] -or $Value -is [Collections.IList]){$items=@();foreach($v in $Value){$items+=ConvertTo-AcCanonical $v};return '['+($items -join ',')+']'}
 return ConvertTo-Json $Value -Compress -Depth 16
}
function Get-AcOptional($Object,[string]$Name){if($Object.PSObject.Properties.Name -contains $Name){return $Object.$Name};return $null}
function ConvertTo-AcAsciiLower([string]$Value){$chars=$Value.ToCharArray();for($i=0;$i -lt $chars.Length;$i++){if([int]$chars[$i] -ge 65 -and [int]$chars[$i] -le 90){$chars[$i]=[char]([int]$chars[$i]+32)}};return -join $chars}
function Test-AcRelative([string]$Path){
 if(-not $Path -or $Path.Length -gt 32767 -or $Path -match '^[\\/]|[\x00-\x1f\x7f]'){return $false}
 foreach($p in ($Path.Replace('\','/').Split('/'))){if(-not $p -or $p -in @('.','..') -or $p.Length -gt 255 -or $p -match '[. ]$|[:*?"<>|]' -or ($p.Split('.')[0] -match '^(?i:CON|PRN|AUX|NUL|COM[1-9¹²³]|LPT[1-9¹²³])$')){return $false}};return $true
}
function Assert-AcFields($Value,[string[]]$Fields){if(-not $Value -or (Compare-Object @($Value.PSObject.Properties.Name | Sort-Object) @($Fields | Sort-Object))){throw 'unexpected_object_fields'}}
function Assert-AcStrings($Value,[int]$Limit=256,[bool]$Empty=$false){if($Value -isnot [Array] -or $Value.Count -gt $Limit -or (-not $Empty -and -not $Value.Count)){throw 'invalid_string_array'};foreach($v in $Value){if($v -isnot [string] -or -not $v -or $v.Length -gt 512){throw 'invalid_string'}}}
function Assert-AcRules($Rules){
 Assert-AcFields $Rules @('schema_version','engine_version','ruleset_version','providers','file_signals','corroborations','system_signals','auxiliary_directory_names','notes')
 if($Rules.schema_version -isnot [int] -or $Rules.schema_version -ne 1 -or $Rules.engine_version -isnot [int] -or $Rules.engine_version -ne 1 -or $Rules.ruleset_version -notmatch '^[0-9.\-]{1,40}$' -or [Text.Encoding]::UTF8.GetByteCount((ConvertTo-AcCanonical $Rules)) -gt 131072){throw 'unsupported_rules'}
 $ids=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::Ordinal);$providers=@{};$signals=@{}
 foreach($spec in @(@('providers',32),@('file_signals',128),@('corroborations',32),@('system_signals',64))){if($Rules.($spec[0]) -isnot [Array] -or $Rules.($spec[0]).Count -gt $spec[1]){throw 'rules_count_limit'}}
 if(-not $Rules.providers.Count -or -not $Rules.file_signals.Count){throw 'empty_ruleset'}
 foreach($item in @($Rules.providers)+@($Rules.file_signals)+@($Rules.corroborations)+@($Rules.system_signals)){if($item.id -isnot [string] -or $item.id -notmatch '^[a-z0-9_.]{1,80}$' -or -not $ids.Add($item.id)){throw 'invalid_or_duplicate_id'}}
 foreach($p in $Rules.providers){Assert-AcFields $p @('id','name','source_ids');if($p.name -isnot [string] -or -not $p.name -or $p.name.Length -gt 128){throw 'invalid_provider_name'};Assert-AcStrings $p.source_ids;$providers[$p.id]=$p.name}
 foreach($s in $Rules.file_signals){Assert-AcFields $s @('id','provider','basenames','parent_names','role','source_ids');if(-not $providers.ContainsKey($s.provider) -or $s.role -cnotin @('component','support')){throw 'invalid_signal_reference'};Assert-AcStrings $s.basenames;Assert-AcStrings $s.parent_names 256 $true;Assert-AcStrings $s.source_ids;foreach($n in @($s.basenames)+@($s.parent_names)){if(-not (Test-AcRelative $n) -or $n -match '[\\/]'){throw 'literal_basename_required'}};$signals[$s.id]=$s.provider}
 foreach($c in $Rules.corroborations){Assert-AcFields $c @('id','provider','algorithm','requires');Assert-AcStrings $c.requires;$expected=switch -CaseSensitive ($c.algorithm){'eac_eos_layout_v1'{@('eac_eos.setup','eac_eos.settings','eac_eos.bootstrap')};'battleye_layout_v1'{@('battleye.service','battleye.install')};default{throw 'unsupported_corroboration'}};$owner=if($c.algorithm -ceq 'eac_eos_layout_v1'){'eac_eos'}else{'battleye'};if($c.provider -cne $owner -or (Compare-Object @($expected|Sort-Object) @($c.requires|Sort-Object))){throw 'invalid_corroboration_reference'};foreach($id in $c.requires){if($signals[$id] -cne $owner){throw 'invalid_corroboration_reference'}}}
 foreach($s in $Rules.system_signals){Assert-AcFields $s @('id','provider','kind','locator','source_ids');Assert-AcStrings $s.source_ids;if(-not $providers.ContainsKey($s.provider) -or $s.kind -cnotin @('service','known_folder_file') -or -not (Test-AcRelative $s.locator)){throw 'invalid_system_signal'};if($s.kind -ceq 'service' -and ($s.locator -match '[\\/]' -or $s.locator.Length -gt 256)){throw 'invalid_service_name'};if($s.kind -ceq 'known_folder_file' -and $s.locator.Split('/')[0] -cnotin @('ProgramFiles','ProgramFilesX86','ProgramFilesCommonX86')){throw 'unsupported_known_folder'}}
 Assert-AcStrings $Rules.auxiliary_directory_names 256 $true;Assert-AcStrings $Rules.notes 256 $true;foreach($n in $Rules.auxiliary_directory_names){if(-not (Test-AcRelative $n) -or $n -match '[\\/]'){throw 'invalid_auxiliary_directory'}}
}
function Invoke-HubAntiCheatPolicy($Rules,$Snapshot){
 $r=[ordered]@{schema_version=1;digest_encoding='neurotic-canonical-json-v1';ruleset_version='unavailable';rules_digest='';target_id='unavailable';selected_exe='unavailable';game_state='not_found';headline='incomplete';scan_status='incomplete';findings=@();system_context=@();system_status='not_requested';issues=@();safety_verified=$false;protection_active=$null;block_for_anticheat=$false;requires_ack=$true;evidence_digest=''}
 try{Assert-AcRules $Rules}catch{$r.issues=@('rules_invalid');$r.evidence_digest=Get-AcHash @{issues=$r.issues};return [pscustomobject]$r}
 $r.ruleset_version=$Rules.ruleset_version;$r.rules_digest=Get-AcHash $Rules
 try{Assert-AcFields $Snapshot @('schema_version','target_id','selected_exe','scan_status','issues','files','system_status','system','catalog');if($Snapshot.schema_version -isnot [int] -or $Snapshot.schema_version -ne 1 -or $Snapshot.target_id -isnot [string] -or -not $Snapshot.target_id -or $Snapshot.target_id.Length -gt 512 -or -not (Test-AcRelative $Snapshot.selected_exe) -or $Snapshot.scan_status -cnotin @('complete','incomplete','cancelled') -or $Snapshot.system_status -cnotin @('not_requested','complete','incomplete')){throw 'invalid_snapshot'};Assert-AcStrings $Snapshot.issues 256 $true;foreach($k in @('files','system','catalog')){if($Snapshot.$k -isnot [Array]){throw 'invalid_snapshot_array'}}}catch{$r.issues=@('snapshot_invalid');$r.evidence_digest=Get-AcHash @{issues=$r.issues};return [pscustomobject]$r}
 $r.target_id=$Snapshot.target_id;$r.selected_exe=$Snapshot.selected_exe.Replace('\','/');$r.scan_status=$Snapshot.scan_status;$r.system_status=$Snapshot.system_status
 $issues=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::Ordinal);foreach($i in $Snapshot.issues){[void]$issues.Add($i)};$fingerprints=New-Object Collections.Generic.List[object];$by=@{};$findings=@{};$names=@{};foreach($p in $Rules.providers){$names[$p.id]=$p.name};$seen=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase)
 $level=@{not_found=0;documented=1;possible=2;detected=3}
 function Add-AcFinding([string]$Provider,[string]$State,[string]$Reason,$Evidence){if(-not $findings.ContainsKey($Provider)){$findings[$Provider]=[ordered]@{provider=$Provider;name=$names[$Provider];state='not_found';identity_verified=$false;reasons=@();evidence=@()}};$f=$findings[$Provider];if($level[$State] -gt $level[$f.state]){$f.state=$State};$f.reasons+=,$Reason;$f.evidence+=@($Evidence)}
 if($Snapshot.files.Count -gt 256){[void]$issues.Add('candidate_limit')}
 foreach($raw in @($Snapshot.files | Select-Object -First 256)){
  try{
   $required=@('path','pe','read_status','size','identity','digest','signature_status');$fields=@($raw.PSObject.Properties.Name);if(@($required|Where-Object {$_ -cnotin $fields}).Count -or @($fields|Where-Object {$_ -cnotin ($required+@('text','json_object','config_hash'))}).Count -or -not (Test-AcRelative $raw.path) -or $raw.pe -isnot [bool] -or $raw.read_status -cnotin @('ok','denied','unavailable','changed')){throw 'invalid_observation'}
   $nonok=$raw.read_status -cne 'ok';if(-not ($null -eq $raw.size -and $nonok) -and (($raw.size -isnot [int] -and $raw.size -isnot [long]) -or $raw.size -lt 0)){throw 'invalid_size'};if(-not ($null -eq $raw.identity -and $nonok) -and ($raw.identity -isnot [string] -or -not $raw.identity -or $raw.identity.Length -gt 512)){throw 'invalid_identity'};if(-not ($null -eq $raw.digest -and $nonok) -and ($raw.digest -isnot [string] -or $raw.digest -cnotmatch '^[0-9a-f]{64}$')){throw 'invalid_digest'};if($raw.signature_status -cnotin @('not_checked','offline_valid','unsigned','invalid','offline_unavailable')){throw 'invalid_signature_status'}
   $path=$raw.path.Replace('\','/');if(-not $seen.Add($path)){throw 'duplicate_or_ambiguous_path'};$parts=$path.Split('/');$base=ConvertTo-AcAsciiLower $parts[-1];$parent=if($parts.Count -gt 1){$n=ConvertTo-AcAsciiLower $parts[-2];$n}else{''};$parentPath=if($parts.Count -gt 1){($parts[0..($parts.Count-2)] -join '/').ToLowerInvariant()}else{''}
   $rawText=Get-AcOptional $raw 'text';$configHash=Get-AcOptional $raw 'config_hash';if($rawText -is [string]){$sha=[Security.Cryptography.SHA256]::Create();try{$configHash=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($rawText)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
   $fingerprints.Add([ordered]@{path=$path;identity=$raw.identity;digest=$raw.digest;size=$raw.size;read_status=$raw.read_status;pe=$raw.pe;signature_status=$raw.signature_status;config_hash=$configHash})
   if($nonok){[void]$issues.Add('candidate_read_'+$raw.read_status)}
   foreach($s in $Rules.file_signals){if($base -cnotin @($s.basenames|ForEach-Object {ConvertTo-AcAsciiLower $_})){continue};$placed=-not $s.parent_names.Count -or $parent -cin @($s.parent_names|ForEach-Object {ConvertTo-AcAsciiLower $_});if($s.role -ceq 'support' -and -not $placed){continue};$aux=$false;foreach($part in @($parts|Select-Object -SkipLast 1)){if((ConvertTo-AcAsciiLower $part) -cin @($Rules.auxiliary_directory_names|ForEach-Object {ConvertTo-AcAsciiLower $_})){$aux=$true}}
    $e=[ordered]@{signal_id=$s.id;path=$path;read_status=$raw.read_status;pe=$raw.pe;signature_status=$raw.signature_status;auxiliary=$aux;expected_layout=[bool]$placed};$obj=$false
    if($s.id -ceq 'eac_eos.settings' -and -not $nonok){try{if($raw.PSObject.Properties.Name -contains 'json_object'){$obj=[bool]$raw.json_object}else{if($rawText -isnot [string] -or [Text.Encoding]::UTF8.GetByteCount($rawText) -gt 65536){throw 'config_limit'};if(-not ('NeuRoticHubJson' -as [type])){Add-Type -Path (Join-Path $PSScriptRoot 'NeuRotic-HubJson.cs')};$obj=[NeuRoticHubJson]::IsNonemptyConfigObject($rawText)}}catch{[void]$issues.Add('candidate_config_unreadable')}}
    if(-not $by.ContainsKey($s.id)){$by[$s.id]=@()};$by[$s.id]+=,[pscustomobject]@{evidence=$e;parent=$parentPath;identity=$raw.identity;json_object=$obj}
    if($s.role -ceq 'component'){Add-AcFinding $s.provider 'possible' 'filename_indicator' @($e)}
   }
  }catch{[void]$issues.Add('invalid_candidate_observation')}
 }
 function Test-AcUsable($o,[bool]$Pe=$false){return $o -and $o.evidence.expected_layout -and -not $o.evidence.auxiliary -and $o.evidence.read_status -ceq 'ok' -and (-not $Pe -or $o.evidence.pe)}
 foreach($c in $Rules.corroborations){if($c.algorithm -ceq 'eac_eos_layout_v1'){foreach($setup in $by['eac_eos.setup']){$package=if($setup.parent.Contains('/')){$setup.parent.Substring(0,$setup.parent.LastIndexOf('/'))}else{''};foreach($settings in $by['eac_eos.settings']){foreach($boot in $by['eac_eos.bootstrap']){if((Test-AcUsable $setup $true) -and (Test-AcUsable $settings) -and $settings.json_object -and (Test-AcUsable $boot $true) -and $settings.parent -ceq $setup.parent -and $boot.parent -ceq $package -and @(@($setup.identity,$settings.identity,$boot.identity)|Select-Object -Unique).Count -eq 3){Add-AcFinding $c.provider 'detected' $c.id @($setup.evidence,$settings.evidence,$boot.evidence)}}}}}else{foreach($svc in $by['battleye.service']){foreach($install in $by['battleye.install']){if((Test-AcUsable $svc $true) -and (Test-AcUsable $install) -and $svc.parent -ceq $install.parent -and $svc.identity -cne $install.identity){Add-AcFinding $c.provider 'detected' $c.id @($svc.evidence,$install.evidence)}}}}}
 foreach($rec in @($Snapshot.catalog|Select-Object -First 128)){try{Assert-AcFields $rec @('provider','source_id','match','record_id','app_id');foreach($v in $rec.PSObject.Properties.Value){if($v -isnot [string] -or -not $v -or $v.Length -gt 512){throw 'invalid_catalog'}};if($names.ContainsKey($rec.provider) -and $rec.match -ceq 'storefront_id'){Add-AcFinding $rec.provider 'documented' 'curated_storefront_record' @($rec)}}catch{}}
 if($Snapshot.catalog.Count -gt 128){[void]$issues.Add('catalog_limit')};$sys=@{};foreach($s in $Rules.system_signals){$sys[$s.id]=$s};foreach($o in @($Snapshot.system|Select-Object -First 64)){if(-not $o -or -not $sys.ContainsKey([string]$o.signal_id)){$r.system_status='incomplete';continue};if($o.status -ceq 'present'){$running=Get-AcOptional $o 'running';if($running -isnot [bool]){$running=$null};$r.system_context+=,[ordered]@{provider=$sys[$o.signal_id].provider;signal_id=$o.signal_id;association='system_only';running=$running}}elseif($o.status -cne 'absent'){$r.system_status='incomplete'}};if($Snapshot.system.Count -gt 64){$r.system_status='incomplete'}
 $r.system_context=@($r.system_context|Sort-Object {ConvertTo-AcCanonical $_} -Unique);$r.findings=@($findings.Values|Sort-Object provider);foreach($f in $r.findings){$f.reasons=@($f.reasons|Sort-Object -Unique);$f.evidence=@($f.evidence|Sort-Object {ConvertTo-AcCanonical $_} -Unique)};$r.issues=@($issues|Sort-Object);if($issues.Count -and $r.scan_status -ceq 'complete'){$r.scan_status='incomplete'};foreach($f in $r.findings){if($level[$f.state] -gt $level[$r.game_state]){$r.game_state=$f.state}}
 $cancel=$r.scan_status -ceq 'cancelled';$r.headline=if($cancel){'cancelled'}elseif($r.game_state -cne 'not_found'){$r.game_state}elseif($r.scan_status -cne 'complete'){'incomplete'}else{'not_found'};$r.requires_ack=-not $cancel -and ($r.findings.Count -gt 0 -or $r.scan_status -cne 'complete');$r.evidence_digest=Get-AcHash @{target=$r.target_id;exe=$r.selected_exe;rules=$r.rules_digest;files=@($fingerprints|Sort-Object {ConvertTo-AcCanonical $_});findings=$r.findings;scan_status=$r.scan_status;issues=$r.issues};return [pscustomobject]$r
}
