#include "LanguagePack.h"
#include <algorithm>
#include <regex>
#include <set>
namespace Neurotic::Localization {
std::string LanguageIssue::English()const{return code.empty()?std::string{}:Format(Resolve({&CanonicalEnglish()},code),parameters);}
namespace {struct PackError:std::runtime_error{LanguageIssue issue;PackError(std::string code,NamedArguments args={}):std::runtime_error(LanguageIssue{code,args}.English()),issue{std::move(code),std::move(args)}{}};}
bool ValidLocale(std::string_view locale){return locale.size()<=63&&std::regex_match(locale.begin(),locale.end(),std::regex("(?:(?:[A-Za-z]{2,3}(?:-[A-Za-z]{3}){0,3}|[A-Za-z]{4}|[A-Za-z]{5,8})(?:-[A-Za-z]{4})?(?:-(?:[A-Za-z]{2}|[0-9]{3}))?(?:-(?:[A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(?:-[0-9A-WY-Za-wy-z](?:-[A-Za-z0-9]{2,8})+)*(?:-[xX](?:-[A-Za-z0-9]{1,8})+)?|[xX](?:-[A-Za-z0-9]{1,8})+)"));}
bool UsableText(std::string_view text){if(text.empty()||text.size()>32768)return false;bool visible=false;for(unsigned char c:text){if((c<32&&c!='\n'&&c!='\r'&&c!='\t')||c==127)return false;visible|=c>32;}if(!visible)return false;try{(void)Json(std::string(text)).dump(-1,' ',false,Json::error_handler_t::strict);}catch(...){return false;}return true;}
namespace {
std::vector<std::string> Tokens(std::string_view text){static const std::regex pattern(R"(%(?:[-+#0]*(?:\d+|\*)?(?:\.(?:\d+|\*))?(?:hh|ll|[hljztL]|I64)?[diuoxXfFeEgGaAcspn]|%)|\{[A-Za-z_][A-Za-z0-9_]*\})");std::string s(text);std::vector<std::string> tokens;for(std::sregex_iterator i(s.begin(),s.end(),pattern),end;i!=end;++i)tokens.push_back(i->str());return tokens;}
void Fields(const Json& object,std::initializer_list<const char*> allowed){if(!object.is_object())throw PackError("desktop.languageerror.87a532b4348e");for(auto it=object.begin();it!=object.end();++it)if(std::find_if(allowed.begin(),allowed.end(),[&](const char* field){return it.key()==field;})==allowed.end())throw PackError("desktop.languageerror.3e6684b9fe11",{{"field",it.key()}});}
std::string Text(const Json& object,const char* key,bool required=true){if(!object.contains(key)){if(required)throw PackError("desktop.languageerror.e5ba5b0b7419",{{"field",std::string(key)}});return {};}if(!object[key].is_string())throw PackError("desktop.languageerror.33008eded48d",{{"field",std::string(key)}});auto value=object[key].get<std::string>();if(!value.empty()&&!UsableText(value))throw PackError("desktop.languageerror.119ba8b352ed",{{"field",std::string(key)}});if(required&&value.empty())throw PackError("desktop.languageerror.94c69b630675",{{"field",std::string(key)}});if(std::string_view(key)=="name"||std::string_view(key)=="language"||std::string_view(key)=="author"||std::string_view(key)=="version"){if(value.size()>255||value.find_first_of("\n\r\t")!=std::string::npos)throw PackError("desktop.languages.metadata_bound",{{"field",std::string(key)}});}return value;}
}
LanguageIssue TranslationIssue(std::string_view text,const EnglishEntry& entry){
 if(!UsableText(text))return LanguageIssue{"desktop.languageerror.a0f8d8abf9b5",{}};
 if(!entry.lineBreaks&&(text.find('\n')!=text.npos||text.find('\r')!=text.npos))return LanguageIssue{"desktop.languageerror.0ec863dfc8a0",{}};
 for(const auto& term:entry.preserve)if(text.find(term)==text.npos)return LanguageIssue{"desktop.languageerror.b5b141b1bbf3",{{"term",term}}};
 auto source=Tokens(entry.english),target=Tokens(text);auto named=[](const std::string& s){return s.starts_with('{');};std::vector<std::string> sourceNamed,targetNamed,sourcePrintf,targetPrintf;
 for(const auto& token:source)(named(token)?sourceNamed:sourcePrintf).push_back(token);for(const auto& token:target)(named(token)?targetNamed:targetPrintf).push_back(token);std::sort(sourceNamed.begin(),sourceNamed.end());std::sort(targetNamed.begin(),targetNamed.end());
 if(sourceNamed!=targetNamed||sourcePrintf!=targetPrintf)return LanguageIssue{"desktop.languageerror.fb90bdd49d17",{}};
 // Reject unrecognized braces/percent directives instead of interpreting them.
 auto stripped=std::regex_replace(std::string(text),std::regex(R"(%(?:[-+#0]*(?:\d+|\*)?(?:\.(?:\d+|\*))?(?:hh|ll|[hljztL]|I64)?[diuoxXfFeEgGaAcspn]|%)|\{[A-Za-z_][A-Za-z0-9_]*\})"),"");
 auto englishStripped=std::regex_replace(entry.english,std::regex(R"(%(?:[-+#0]*(?:\d+|\*)?(?:\.(?:\d+|\*))?(?:hh|ll|[hljztL]|I64)?[diuoxXfFeEgGaAcspn]|%)|\{[A-Za-z_][A-Za-z0-9_]*\})"),"");
 for(char c:{'%','{','}'})if(std::count(stripped.begin(),stripped.end(),c)!=std::count(englishStripped.begin(),englishStripped.end(),c))return LanguageIssue{"desktop.languageerror.fd14da489621",{}};
 return {};
}
std::string TranslationError(std::string_view text,const EnglishEntry& entry){return TranslationIssue(text,entry).English();}
PackValidation ValidatePack(std::string_view bytes,const EnglishCatalog& english){PackValidation result;try{
 if(bytes.size()>16777216)throw PackError("desktop.languageerror.8eab000800ba");
 std::vector<std::set<std::string>> keys;auto callback=[&](int depth,nlohmann::json::parse_event_t event,Json& value){if(depth>16)throw PackError("desktop.languageerror.af46d899ed8a");if(event==Json::parse_event_t::object_start)keys.emplace_back();else if(event==Json::parse_event_t::key){if(keys.empty()||!keys.back().insert(value.get<std::string>()).second)throw PackError("desktop.languageerror.51856d9f75b7");}else if(event==Json::parse_event_t::object_end)keys.pop_back();return true;};
 auto doc=Json::parse(bytes.begin(),bytes.end(),callback);Fields(doc,{"formatVersion","packId","locale","language","name","author","version","contact","projectUrl","sourcePack","desktop","in_game","coverage"});
 if(!doc.contains("formatVersion")||!doc["formatVersion"].is_number_integer()||doc["formatVersion"]!=1)throw PackError("desktop.languageerror.6718fef50096");
 result.pack.id=Text(doc,"packId");if(result.pack.id.size()>96||!std::regex_match(result.pack.id,std::regex("[A-Za-z0-9][A-Za-z0-9_.-]*")))throw PackError("desktop.languageerror.59ad3ea71226");result.pack.locale=Text(doc,"locale");if(!ValidLocale(result.pack.locale))throw PackError("desktop.languageerror.6bbe06e39359");result.pack.name=Text(doc,"name");(void)Text(doc,"language");(void)Text(doc,"author",false);(void)Text(doc,"version");(void)Text(doc,"contact",false);(void)Text(doc,"projectUrl",false);(void)Text(doc,"sourcePack",false);
 if(doc.contains("coverage")){Fields(doc["coverage"],{"desktop","in_game","reviewed","stale","invalid","total"});for(auto it=doc["coverage"].begin();it!=doc["coverage"].end();++it)if(!it.value().is_number_unsigned()&&!it.value().is_number_integer())throw PackError("desktop.languageerror.ee4b988cabef");}
 size_t count=0;std::set<std::string> ids;for(auto surface:{"desktop","in_game"}){if(!doc.contains(surface)||!doc[surface].is_array())throw PackError("desktop.languageerror.ca8b8a356dad",{{"field",std::string(surface)}});for(const auto& item:doc[surface]){
 if(++count>65536)throw PackError("desktop.languageerror.0fa22ee62e43");Fields(item,{"id","translation","revision","note","surface","section","control","english","context","placeholders","preserve","line_breaks"});auto id=Text(item,"id");if(id.size()>256||!ids.insert(id).second)throw PackError("desktop.languageerror.50b75d58acc8");
 if(!item.contains("translation")||!item["translation"].is_string())throw PackError("desktop.languageerror.e48c8b24c446");auto text=item["translation"].get<std::string>();auto note=Text(item,"note",false);unsigned revision=0;if(item.contains("revision")&&item["revision"].is_number_unsigned())revision=item["revision"].get<unsigned>();else if(item.contains("revision")&&item["revision"].is_number_integer()&&item["revision"].get<int64_t>()>=0&&item["revision"].get<int64_t>()<=UINT32_MAX)revision=item["revision"].get<unsigned>();else throw PackError("desktop.languageerror.b69c6122ae41");
 auto known=english.find(id);if(known==english.end()){if(!text.empty()&&!UsableText(text))result.errors.push_back({id,"Obsolete translation is invalid text.","desktop.languageerror.287d2724fe66",{}});result.pack.obsolete.push_back(item);continue;}
 auto issue=known->second.surface!=surface?LanguageIssue{"desktop.languageerror.7d1e221bc11c",{}}:TranslationIssue(text,known->second);if(!issue.code.empty()){if(!text.empty())result.errors.push_back({id,issue.English(),issue.code,issue.parameters});continue;}result.pack.entries.emplace(id,Translation{std::move(text),std::move(note),revision});
 }}result.pack.document=std::move(doc);result.accepted=true;
 }catch(const PackError& error){result.pack={};result.error=error.what();result.errorCode=error.issue.code;result.errorParameters=error.issue.parameters;}catch(const std::exception& error){result.pack={};result.error=error.what();result.errorCode="desktop.languageerror.5ab262f34f8c";result.errorParameters={{"detail",std::string(error.what())}};}return result;}
}
