#include <menu/Localization.h>
#pragma once
#include "ObjectRules.h"
#include <imgui/imgui.h>
#include <array>
#include <functional>
#include <optional>

namespace Neurotic::Semantic::Rules {
struct Host {
    bool desktop=false;
    std::function<std::string()> importFile;
    std::function<bool(const std::string&)> exportFile;
    std::function<void()> globalControls;
    std::string runtime=Neurotic::UiMessage("ingame.objectruleeditor.start_live_inspection_in_character_inspector_to__c74f98f8", "Start live inspection in Character Inspector to see detections. Enable People and objects there for non-person classes.");
};
struct Editor {
    std::string selected,draftId,pendingSelect,message,importBytes,importError;
    Json draft;uint64_t draftRevision=0,viewRevision=~uint64_t(0);bool dirty=false,descending=false,detail=false,collapsed=false;
    int mode=0,filter=0,importMode=0;std::vector<size_t> view;
    std::array<char,513> search{},phrase{},label{};std::string lastSearch;int lastFilter=-1;bool lastDescending=false;
    std::optional<ImportPreview> preview;
};
inline bool TextEdit(const char* label,Json& value,size_t max=513){std::vector<char> buffer(max,0);auto text=value.get<std::string>();std::copy_n(text.data(),std::min(text.size(),max-1),buffer.data());ImGui::TextUnformatted(label);ImGui::SetNextItemWidth(-1);if(ImGui::InputText((std::string("##")+label).c_str(),buffer.data(),buffer.size())){value=std::string(buffer.data());return true;}return false;}
inline bool FloatEdit(const char* label,Json& value,float lo,float hi){float v=value.get<float>();ImGui::TextUnformatted(label);ImGui::SetNextItemWidth(-1);if(ImGui::SliderFloat((std::string("##")+label).c_str(),&v,lo,hi,"%.2f")){value=v;return true;}return false;}
// In-game slider resets preserve the editor's existing draft/overlay commit policy.
inline bool ResetEdit(const Host& host,const char* id,Json& value,const Json& baseline){
    if(host.desktop)return false;
    ImGui::PushID(id);const bool reset=ImGui::SmallButton(Neurotic::UiLiteral("ingame.menu-common.reset_14de5ef1", "Reset"));ImGui::PopID();
    if(reset)value=baseline;return reset;
}
inline bool BoolEdit(const char* label,Json& value){bool v=value.get<bool>();if(ImGui::Checkbox(label,&v)){value=v;return true;}return false;}
inline bool ColorEdit(const char* label,Json& value){auto s=value.get<std::string>();unsigned n=std::stoul(s.substr(1),nullptr,16);float c[]={float(n>>16)/255,float((n>>8)&255)/255,float(n&255)/255};if(ImGui::ColorEdit3(label,c,ImGuiColorEditFlags_NoInputs)){char text[8];std::snprintf(text,sizeof(text),"#%02x%02x%02x",unsigned(c[0]*255+.5f),unsigned(c[1]*255+.5f),unsigned(c[2]*255+.5f));value=text;return true;}return false;}
inline void LoadDraft(Editor& e,const Snapshot& s){auto i=std::find_if(s.rules.begin(),s.rules.end(),[&](const Rule& r){return r.id==e.selected;});e.draftId=e.selected;e.draftRevision=s.revision;e.draft=i==s.rules.end()?Json():i->value;e.dirty=false;}
inline void Select(Editor& e,const std::string& id){if(id==e.selected){e.detail=true;return;}if(e.dirty){e.pendingSelect=id;}else{e.selected=id;e.detail=true;}}
inline bool ApplyDraft(Store& store,Editor& e){auto s=store.Read();auto p=s->profile;auto i=std::find_if(p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")].begin(),p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")].end(),[&](const Json& r){return r[Neurotic::UiLiteral("ingame.objectruleeditor.id_1304cb9d", "id")]==e.draftId;});if(i==p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")].end()){e.message=Neurotic::UiMessage("ingame.objectruleeditor.rule_was_removed_reload_the_editor_d0ebc2a3", "Rule was removed. Reload the editor.");return false;}*i=e.draft;auto ack=store.Commit(e.draftRevision,p);e.message=ack.reason;if(ack.accepted){e.dirty=false;e.draftRevision=store.Read()->revision;}return ack.accepted;}
inline void PreviewImport(const std::shared_ptr<const Snapshot>& snapshot,Editor& e,int mode){
    e.importMode=mode;e.preview.reset();e.importError.clear();
    try{e.preview=BuildImport(snapshot,e.importBytes,static_cast<ImportMode>(mode));}catch(const std::exception& ex){e.importError=ex.what();}
}
inline void DrawEditor(Store& store,Editor& e,const Host& host){
    ImGui::PushID(&store);const float unit=ImGui::GetFontSize();const float width=ImGui::GetContentRegionAvail().x;
    const bool compact=width<unit*44;auto s=store.Read();
    if(!host.desktop){ImGui::SetNextItemWidth(std::min(width,unit*13));if(ImGui::BeginCombo(Neurotic::UiLiteral("ingame.objectruleeditor.activity_e350d11d", "Activity"),e.mode?Neurotic::UiLiteral("ingame.objectruleeditor.inspect_333df58d", "Inspect"):Neurotic::UiLiteral("ingame.objectruleeditor.off_dc516be5", "Off"))){
        if(ImGui::Selectable(Neurotic::UiLiteral("ingame.objectruleeditor.off_dc516be5", "Off"),e.mode==0))e.mode=0;
        if(ImGui::Selectable(Neurotic::UiLiteral("ingame.objectruleeditor.inspect_333df58d", "Inspect"),e.mode==1))e.mode=1;
        ImGui::BeginDisabled();ImGui::Selectable(Neurotic::UiLiteral("ingame.objectruleeditor.apply_recipe_no_qualified_masks_bbe21f0a", "Apply recipe (no qualified masks)"));ImGui::Selectable(Neurotic::UiLiteral("ingame.objectruleeditor.experiment_no_qualified_backend_a79b0940", "Experiment (no qualified backend)"));ImGui::EndDisabled();ImGui::EndCombo();}}
    if(host.desktop){
        ImGui::BeginDisabled(e.dirty);if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.import_json_50cda3d6", "Import JSON..."))){try{if(host.importFile){e.importBytes=host.importFile();if(!e.importBytes.empty()){Parse(e.importBytes);PreviewImport(s,e,0);ImGui::OpenPopup(Neurotic::UiLiteral("ingame.objectruleeditor.import_preview_69adef80", "Import preview"));}}}catch(const std::exception& ex){e.message=ex.what();}}ImGui::EndDisabled();
        ImGui::SameLine();if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.export_json_1c1311ff", "Export JSON...")))ImGui::OpenPopup(Neurotic::UiLiteral("ingame.objectruleeditor.export_rules_ebe23893", "Export rules"));
        if(ImGui::BeginPopup(Neurotic::UiLiteral("ingame.objectruleeditor.export_rules_ebe23893", "Export rules"))){for(bool selected:{false,true})if(ImGui::Selectable(selected?Neurotic::UiLiteral("ingame.objectruleeditor.selected_rule_88397feb", "Selected rule"):Neurotic::UiLiteral("ingame.objectruleeditor.all_configured_rules_36f58338", "All configured rules"))){try{auto p=s->profile;if(selected){p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")]=Json::array();for(const auto& r:s->rules)if(r.id==e.selected)p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")].push_back(r.value);}if(host.exportFile&&host.exportFile(Export(p)))e.message=Neurotic::UiMessage("ingame.objectruleeditor.exported_configured_values_inherited_settings_re_c1b9437c", "Exported configured values; inherited settings remain inherited.");}catch(const std::exception& ex){e.message=ex.what();}}ImGui::EndPopup();}
    }
    if(host.desktop||e.mode)ImGui::TextWrapped("%s",Neurotic::Translate(host.runtime.c_str()).c_str());
    ImGui::SetNextItemWidth(std::max(unit*5,width-(compact?0:unit*24)));
    if(ImGui::IsWindowFocused(ImGuiFocusedFlags_ChildWindows)&&ImGui::GetIO().KeyCtrl&&ImGui::IsKeyPressed(ImGuiKey_F))ImGui::SetKeyboardFocusHere();
    ImGui::InputTextWithHint("##Search",Neurotic::UiLiteral("ingame.objectruleeditor.search_words_8739f392", "Search words..."),e.search.data(),e.search.size());
    if(!compact)ImGui::SameLine();if(ImGui::Button(e.descending?"Z-A":"A-Z"))e.descending=!e.descending;
    ImGui::SameLine();ImGui::SetNextItemWidth(std::min(unit*10,width*.5f));ImGui::Combo("##Filter",&e.filter,Neurotic::UiOptions("ingame.objectruleeditor.all_rules_8e3fb0ae|ingame.objectruleeditor.enabled_90f9fd68|ingame.objectruleeditor.disabled_1b52e3fc|ingame.characterinspectormenu.needs_attention_a6586758|", "All rules\0Enabled\0Disabled\0Needs attention\0"));
    ImGui::SameLine();ImGui::BeginDisabled(e.dirty);if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.add_48ff30f1", "Add"))){e.phrase.fill(0);e.label.fill(0);ImGui::OpenPopup(Neurotic::UiLiteral("ingame.objectruleeditor.add_rule_88df17d4", "Add rule"));}ImGui::EndDisabled();
    if(e.dirty)ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.apply_or_reset_the_current_edit_before_adding_an_cb57e7b6", "Apply or reset the current edit before adding another rule."));
    if(ImGui::BeginPopup(Neurotic::UiLiteral("ingame.objectruleeditor.add_rule_88df17d4", "Add rule"))){
        ImGui::TextUnformatted(Neurotic::UiLiteral("ingame.objectruleeditor.word_or_short_phrase_423eb210", "Word or short phrase"));ImGui::SetNextItemWidth(unit*17);bool enter=ImGui::InputText("##Phrase",e.phrase.data(),e.phrase.size(),ImGuiInputTextFlags_EnterReturnsTrue);
        ImGui::TextUnformatted(Neurotic::UiLiteral("ingame.objectruleeditor.display_label_optional_d852a82c", "Display label (optional)"));ImGui::SetNextItemWidth(unit*17);ImGui::InputText("##Label",e.label.data(),e.label.size());
        if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.add_rule_88df17d4", "Add rule"))||enter){try{auto phrase=std::string(e.phrase.data());auto normalized=Normalize(phrase);Require(!normalized.empty(),Neurotic::UiLiteral("ingame.objectruleeditor.enter_a_word_or_phrase_da86f6dd", "Enter a word or phrase"));std::string existing;for(const auto& r:s->rules)if(r.value[Neurotic::UiLiteral("ingame.objectruleeditor.match_499ac861", "match")][Neurotic::UiLiteral("ingame.objectruleeditor.kind_785c6186", "kind")]==Neurotic::UiLiteral("ingame.objectruleeditor.text_46be5016", "text"))for(const auto& q:r.value[Neurotic::UiLiteral("ingame.objectruleeditor.match_499ac861", "match")][Neurotic::UiLiteral("ingame.objectruleeditor.phrases_66ac6097", "phrases")])if(Normalize(q[Neurotic::UiLiteral("ingame.objectruleeditor.text_46be5016", "text")])==normalized)existing=r.id;
            if(!existing.empty()){e.selected=existing;e.message=Neurotic::UiMessage("ingame.objectruleeditor.that_phrase_already_exists_use_duplicate_for_a_d_4b4f9130", "That phrase already exists. Use Duplicate for a different look.");}else{auto p=s->profile;auto r=NewRule(phrase,e.label[0]?std::string(e.label.data()):phrase);p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")].push_back(r);auto ack=store.Commit(s->revision,p);Require(ack.accepted,ack.reason.c_str());e.selected=r[Neurotic::UiLiteral("ingame.objectruleeditor.id_1304cb9d", "id")];e.message=Neurotic::UiMessage("ingame.objectruleeditor.rule_added_recognition_uses_the_installed_fixed__f372e61c", "Rule added; recognition uses the installed fixed vocabulary.");}e.detail=true;ImGui::CloseCurrentPopup();
        }catch(const std::exception& ex){e.message=ex.what();}}
        ImGui::SameLine();if(ImGui::Button(Neurotic::UiLiteral("ingame.dlssnr-menu.cancel_7e4b3f1d", "Cancel")))ImGui::CloseCurrentPopup();ImGui::EndPopup();}
    if(!e.pendingSelect.empty())ImGui::OpenPopup(Neurotic::UiLiteral("ingame.objectruleeditor.unapplied_edit_c45312dc", "Unapplied edit"));
    if(ImGui::BeginPopupModal(Neurotic::UiLiteral("ingame.objectruleeditor.unapplied_edit_c45312dc", "Unapplied edit"),nullptr,ImGuiWindowFlags_AlwaysAutoResize)){
        ImGui::TextUnformatted(Neurotic::UiLiteral("ingame.objectruleeditor.apply_the_current_edit_before_changing_selection_f161ed5a", "Apply the current edit before changing selection?"));
        if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.keep_apply_bdea9d81", "Keep / Apply"))&&ApplyDraft(store,e)){e.selected=e.pendingSelect;e.pendingSelect.clear();ImGui::CloseCurrentPopup();}
        ImGui::SameLine();if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.discard_d13d6352", "Discard"))){e.dirty=false;e.selected=e.pendingSelect;e.pendingSelect.clear();ImGui::CloseCurrentPopup();}
        ImGui::SameLine();if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.stay_85b2e92b", "Stay"))){e.pendingSelect.clear();ImGui::CloseCurrentPopup();}ImGui::EndPopup();}
    ImGui::SetNextWindowSizeConstraints({0,0},{std::max(240.f,ImGui::GetIO().DisplaySize.x-24),std::max(220.f,ImGui::GetIO().DisplaySize.y-24)});
    if(host.desktop&&ImGui::BeginPopupModal(Neurotic::UiLiteral("ingame.objectruleeditor.import_preview_69adef80", "Import preview"),nullptr,ImGuiWindowFlags_AlwaysAutoResize)){
        ImGui::Text(Neurotic::UiLiteral("ingame.objectruleeditor.current_rules_zu_762ec42a", "Current rules: %zu"),s->rules.size());
        int mode=e.importMode;if(ImGui::Combo(Neurotic::UiLiteral("ingame.objectruleeditor.decision_5669e49d", "Decision"),&mode,Neurotic::UiOptions("ingame.objectruleeditor.add_as_copies_c35e30cf|ingame.objectruleeditor.update_matching_ids_2d535dce|ingame.objectruleeditor.replace_entire_list_7dfdfb78|", "Add as copies\0Update matching IDs\0Replace entire list\0")))PreviewImport(s,e,mode);
        if(e.importMode==2)ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.replaces_all_zu_current_rules_undo_is_available_3d03382e", "Replaces all %zu current rules. Undo is available."),s->rules.size());
        if(!e.importError.empty())ImGui::TextWrapped("%s",Neurotic::Translate(e.importError.c_str()).c_str());
        if(e.preview){ImGui::Text(Neurotic::UiLiteral("ingame.objectruleeditor.proposed_rules_zu_6d135b07", "Proposed rules: %zu"),e.preview->profile[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")].size());
            ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.effects_and_unsupported_controls_remain_inactive_1714f116", "Effects and unsupported controls remain inactive. Import does not start inspection or NR."));
            ImGui::BeginChild(Neurotic::UiLiteral("ingame.objectruleeditor.warnings_89c2a051", "Warnings"),{std::min(unit*26,ImGui::GetIO().DisplaySize.x-64),unit*7},ImGuiChildFlags_Borders);for(const auto& warning:e.preview->warnings)ImGui::TextWrapped("%s",Neurotic::Translate(warning.c_str()).c_str());ImGui::EndChild();
            if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.confirm_import_7dc4fd1e", "Confirm import"))){auto ack=store.Commit(e.preview->revision,e.preview->profile);e.message=ack.reason;if(ack.accepted){e.dirty=false;e.draftId.clear();e.preview.reset();ImGui::CloseCurrentPopup();}}}
        ImGui::SameLine();if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.cancel_import_1b64d7da", "Cancel import"))){e.preview.reset();ImGui::CloseCurrentPopup();}ImGui::EndPopup();}
    s=store.Read();if(e.viewRevision!=s->revision||e.lastSearch!=e.search.data()||e.lastFilter!=e.filter||e.lastDescending!=e.descending){e.view=Sorted(*s,e.search.data(),e.descending,e.filter);e.viewRevision=s->revision;e.lastSearch=e.search.data();e.lastFilter=e.filter;e.lastDescending=e.descending;}
    if(compact){if(ImGui::Button(e.detail?Neurotic::UiLiteral("ingame.objectruleeditor.back_to_rules_d74c35df", "Back to rules"):Neurotic::UiLiteral("ingame.objectruleeditor.selected_rule_88397feb", "Selected rule")))e.detail=!e.detail;}else{if(ImGui::SmallButton(e.collapsed?Neurotic::UiLiteral("ingame.objectruleeditor.show_rules_3678e9a7", "Show rules"):Neurotic::UiLiteral("ingame.objectruleeditor.collapse_rules_988851cd", "Collapse rules")))e.collapsed=!e.collapsed;}
    // Cursor position is already in unscrolled content coordinates.
    const float used=ImGui::GetCursorPosY();
    const float height=std::clamp(ImGui::GetWindowHeight()-used-unit*4,unit*10,unit*36);
    const bool showList=compact?!e.detail:!e.collapsed;const bool showDetail=compact?e.detail:true;
    if(showList){ImGui::BeginChild(Neurotic::UiLiteral("ingame.objectruleeditor.rule_list_96a76d11", "Rule list"),{compact?0:width*.42f,height},ImGuiChildFlags_Borders);
        if(ImGui::BeginTable("Rules",2,ImGuiTableFlags_RowBg|ImGuiTableFlags_ScrollY,{0,std::max(unit*3,ImGui::GetContentRegionAvail().y-unit*3)})){
            ImGui::TableSetupColumn(Neurotic::UiLiteral("ingame.menu-common.on_d2f9df8a", "On"),ImGuiTableColumnFlags_WidthFixed,ImGui::GetFrameHeight());ImGui::TableSetupColumn(Neurotic::UiLiteral("ingame.provider.e3b46304c234", "Object / rule"));ImGui::TableHeadersRow();
            ImGuiListClipper clip;clip.Begin(static_cast<int>(e.view.size()));while(clip.Step())for(int i=clip.DisplayStart;i<clip.DisplayEnd;++i){const auto& r=s->rules[e.view[i]];ImGui::PushID(r.id.c_str());ImGui::TableNextRow(0,ImGui::GetFrameHeightWithSpacing());ImGui::TableNextColumn();bool enabled=r.enabled;if(ImGui::Checkbox("##Enabled",&enabled,true)){auto p=s->profile;p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")][e.view[i]][Neurotic::UiLiteral("ingame.objectruleeditor.enabled_57741bdb", "enabled")]=enabled;auto ack=store.Commit(s->revision,p);e.message=ack.reason;}ImGui::TableNextColumn();if(ImGui::Selectable(r.label.c_str(),r.id==e.selected))Select(e,r.id);ImGui::PopID();}ImGui::EndTable();}
        ImGui::BeginDisabled(e.selected.empty());if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.remove_6ee1dc87", "Remove"))){auto p=s->profile;auto& rules=p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")];rules.erase(std::remove_if(rules.begin(),rules.end(),[&](const Json& r){return r[Neurotic::UiLiteral("ingame.objectruleeditor.id_1304cb9d", "id")]==e.selected;}),rules.end());auto ack=store.Commit(s->revision,p);e.message=ack.reason;if(ack.accepted){e.selected.clear();e.dirty=false;}}ImGui::EndDisabled();ImGui::SameLine();if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.undo_ec7b2ed7", "Undo"))){auto ack=store.Undo(store.Read()->revision);e.message=ack.reason;if(ack.accepted){e.dirty=false;e.draftId.clear();}}ImGui::EndChild();}
    if(showDetail){if(showList&&!compact)ImGui::SameLine();ImGui::BeginChild(Neurotic::UiLiteral("ingame.objectruleeditor.rule_detail_32345436", "Rule detail"),{0,height},ImGuiChildFlags_Borders);s=store.Read();if(e.selected!=e.draftId||(!e.dirty&&e.draftRevision!=s->revision))LoadDraft(e,*s);
        if(e.draft.is_null())ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.select_a_rule_or_add_a_word_to_begin_1b2585a7", "Select a rule, or add a word to begin."));else{
            ImGui::TextWrapped("%s",Neurotic::Translate(e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.label_c6c68cc9", "label")].get<std::string>().c_str()).c_str());ImGui::SetNextItemWidth(-1);
            if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.apply_rule_62d79b0a", "Apply rule")))ApplyDraft(store,e);ImGui::SameLine();if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.reset_draft_901efe96", "Reset draft")))LoadDraft(e,*s);
            if(ImGui::BeginTabBar("Properties",ImGuiTabBarFlags_FittingPolicyScroll)){
                if(ImGui::BeginTabItem(Neurotic::UiLiteral("ingame.objectruleeditor.appearance_d6d2768d", "Appearance"))){const auto originalOverlay=e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.overlay_b6c2ff4b", "overlay")];auto& o=e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.overlay_b6c2ff4b", "overlay")];e.dirty|=BoolEdit(Neurotic::UiLiteral("ingame.objectruleeditor.show_box_3c1c44e5", "Show box"),o[Neurotic::UiLiteral("ingame.objectruleeditor.show_box_48ee19b6", "show_box")]);e.dirty|=BoolEdit(Neurotic::UiLiteral("ingame.objectruleeditor.show_label_c5b6fd1c", "Show label"),o[Neurotic::UiLiteral("ingame.objectruleeditor.show_label_cd317884", "show_label")]);e.dirty|=ColorEdit(Neurotic::UiLiteral("ingame.objectruleeditor.box_color_86214c5e", "Box color"),o[Neurotic::UiLiteral("ingame.objectruleeditor.box_color_srgb_b7381229", "box_color_srgb")]);e.dirty|=ColorEdit(Neurotic::UiLiteral("ingame.objectruleeditor.label_color_5aab33cc", "Label color"),o[Neurotic::UiLiteral("ingame.objectruleeditor.label_color_srgb_5c4324db", "label_color_srgb")]);e.dirty|=FloatEdit(Neurotic::UiLiteral("ingame.objectruleeditor.line_width_d04041c7", "Line width"),o[Neurotic::UiLiteral("ingame.objectruleeditor.line_width_ui_4e9d8383", "line_width_ui")],1,6);e.dirty|=ResetEdit(host,Neurotic::UiLiteral("ingame.objectruleeditor.line_width_d04041c7", "Line width"),o[Neurotic::UiLiteral("ingame.objectruleeditor.line_width_ui_4e9d8383", "line_width_ui")],2.0);e.dirty|=FloatEdit(Neurotic::UiLiteral("ingame.objectruleeditor.opacity_dc4b9873", "Opacity"),o[Neurotic::UiLiteral("ingame.objectruleeditor.opacity_6b90ab52", "opacity")],0,1);e.dirty|=ResetEdit(host,Neurotic::UiLiteral("ingame.objectruleeditor.opacity_dc4b9873", "Opacity"),o[Neurotic::UiLiteral("ingame.objectruleeditor.opacity_6b90ab52", "opacity")],1.0);
                    if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.reset_overlay_5f0a90e4", "Reset overlay"))){o=NewRule(Neurotic::UiLiteral("ingame.objectruleeditor.person_3f21bb01", "person"),Neurotic::UiLiteral("ingame.objectruleeditor.person_847278ec", "Person"))[Neurotic::UiLiteral("ingame.objectruleeditor.overlay_b6c2ff4b", "overlay")];e.dirty=true;}
                    if(o!=originalOverlay){auto profile=s->profile;for(auto& rule:profile[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")])if(rule[Neurotic::UiLiteral("ingame.objectruleeditor.id_1304cb9d", "id")]==e.draftId)rule[Neurotic::UiLiteral("ingame.objectruleeditor.overlay_b6c2ff4b", "overlay")]=o;const auto ack=store.Commit(e.draftRevision,profile);e.message=ack.reason;if(ack.accepted){s=store.Read();e.draftRevision=s->revision;for(const auto& rule:s->rules)if(rule.id==e.draftId)e.dirty=e.draft!=rule.value;}}
                    ImGui::Separator();ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.object_tint_saturation_exposure_and_metallic_app_b9af8fd4", "Object tint, saturation, exposure and metallic appearance are unavailable: the current detector has no silhouette masks. Saved requests are retained inactive."));ImGui::EndTabItem();}
                if(ImGui::BeginTabItem(Neurotic::UiLiteral("ingame.objectruleeditor.match_7dad01e1", "Match"))){e.dirty|=TextEdit(Neurotic::UiLiteral("ingame.objectruleeditor.display_label_febaf493", "Display label"),e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.label_c6c68cc9", "label")],385);auto& match=e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.match_499ac861", "match")];if(match[Neurotic::UiLiteral("ingame.objectruleeditor.kind_785c6186", "kind")]==Neurotic::UiLiteral("ingame.objectruleeditor.text_46be5016", "text")){
                    int index=0;for(auto& q:match[Neurotic::UiLiteral("ingame.objectruleeditor.phrases_66ac6097", "phrases")]){ImGui::PushID(index++);e.dirty|=TextEdit("Phrase",q[Neurotic::UiLiteral("ingame.objectruleeditor.text_46be5016", "text")]);e.dirty|=TextEdit(Neurotic::UiLiteral("ingame.sleekshell.language_990617e3", "Language"),q[Neurotic::UiLiteral("ingame.objectruleeditor.language_70872b59", "language")],36);ImGui::PopID();}
                    if(match[Neurotic::UiLiteral("ingame.objectruleeditor.phrases_66ac6097", "phrases")].size()<8&&ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.add_alternative_79158139", "Add alternative"))){match[Neurotic::UiLiteral("ingame.objectruleeditor.phrases_66ac6097", "phrases")].push_back({{Neurotic::UiLiteral("ingame.objectruleeditor.text_46be5016", "text"),""},{Neurotic::UiLiteral("ingame.objectruleeditor.language_70872b59", "language"),Neurotic::UiLiteral("ingame.objectruleeditor.en_37022273", "en")}});e.dirty=true;}
                    if(match[Neurotic::UiLiteral("ingame.objectruleeditor.phrases_66ac6097", "phrases")].size()>1&&ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.remove_last_alternative_d04fd08e", "Remove last alternative"))){match[Neurotic::UiLiteral("ingame.objectruleeditor.phrases_66ac6097", "phrases")].erase(match[Neurotic::UiLiteral("ingame.objectruleeditor.phrases_66ac6097", "phrases")].size()-1);e.dirty=true;}
                }else if(match[Neurotic::UiLiteral("ingame.objectruleeditor.kind_785c6186", "kind")]==Neurotic::UiLiteral("ingame.objectruleeditor.fixed_class_930f1128", "fixed_class")){e.dirty|=TextEdit(Neurotic::UiLiteral("ingame.objectruleeditor.provider_754db2ad", "Provider"),match[Neurotic::UiLiteral("ingame.objectruleeditor.provider_key_03d8ded2", "provider_key")],321);e.dirty|=TextEdit(Neurotic::UiLiteral("ingame.objectruleeditor.class_3e5381f0", "Class"),match[Neurotic::UiLiteral("ingame.objectruleeditor.class_key_513c60a9", "class_key")],321);}else ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.manual_label_no_live_manual_mask_provider_is_con_ac0b3f92", "Manual label: no live manual-mask provider is connected."));
                    if(match.contains(Neurotic::UiLiteral("ingame.objectruleeditor.threshold_c1a59682", "threshold"))){e.dirty|=FloatEdit(Neurotic::UiLiteral("ingame.objectruleeditor.confidence_cb58f249", "Confidence"),match[Neurotic::UiLiteral("ingame.objectruleeditor.threshold_c1a59682", "threshold")],0,1);e.dirty|=ResetEdit(host,Neurotic::UiLiteral("ingame.objectruleeditor.confidence_cb58f249", "Confidence"),match[Neurotic::UiLiteral("ingame.objectruleeditor.threshold_c1a59682", "threshold")],0.5);int n=match[Neurotic::UiLiteral("ingame.objectruleeditor.max_instances_176a9765", "max_instances")];ImGui::TextUnformatted(Neurotic::UiLiteral("ingame.objectruleeditor.maximum_matches_15c9aebe", "Maximum matches"));ImGui::SetNextItemWidth(-1);if(ImGui::SliderInt("##Maximum matches",&n,1,128)){match[Neurotic::UiLiteral("ingame.objectruleeditor.max_instances_176a9765", "max_instances")]=n;e.dirty=true;}e.dirty|=ResetEdit(host,Neurotic::UiLiteral("ingame.objectruleeditor.maximum_matches_15c9aebe", "Maximum matches"),match[Neurotic::UiLiteral("ingame.objectruleeditor.max_instances_176a9765", "max_instances")],16);}
                    ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.the_installed_detector_recognizes_80_fixed_class_465beaff", "The installed detector recognizes 80 fixed classes. A new word does not train it. The Inspector's global instance limit also applies. English class names and Human (person) are supported."));ImGui::EndTabItem();}
                if(ImGui::BeginTabItem(Neurotic::UiLiteral("ingame.objectruleeditor.nr_97101caf", "NR"))){ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.inherits_current_game_nr_settings_per_object_ble_dcc3441e", "Inherits current game NR settings. Per-object blend and model overrides are unavailable without qualified masks and matching original/NR images."));ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.saved_strategy_s_blend_0f_inactive_0e8be411", "Saved strategy: %s; blend %.0f%% (inactive)"),Neurotic::Translate(e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.nr_739a8e19", "nr")][Neurotic::UiLiteral("ingame.objectruleeditor.strategy_e72d08d9", "strategy")].get<std::string>().c_str()).c_str(),100*e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.nr_739a8e19", "nr")][Neurotic::UiLiteral("ingame.objectruleeditor.blend_amount_dc71a846", "blend_amount")].get<double>());if(host.globalControls)host.globalControls();ImGui::EndTabItem();}
                if(ImGui::BeginTabItem(Neurotic::UiLiteral("ingame.objectruleeditor.advanced_cfbc9ae1", "Advanced"))){int priority=e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.priority_c7368567", "priority")];ImGui::TextUnformatted(Neurotic::UiLiteral("ingame.objectruleeditor.priority_ea8a4009", "Priority"));ImGui::SetNextItemWidth(-1);if(ImGui::SliderInt("##Priority",&priority,0,1000)){e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.priority_c7368567", "priority")]=priority;e.dirty=true;}e.dirty|=ResetEdit(host,Neurotic::UiLiteral("ingame.objectruleeditor.priority_ea8a4009", "Priority"),e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.priority_c7368567", "priority")],100);ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.mask_feather_grow_shrink_unavailable_no_mask_pro_3d565204", "Mask feather/grow/shrink: unavailable (no mask provider). Overlapping box styles use the highest priority, then rule ID. List sorting never changes priority."));ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.rule_id_s_9eb876c6", "Rule ID: %s"),Neurotic::Translate(e.selected.c_str()).c_str());for(const auto& c:e.draft[Neurotic::UiLiteral("ingame.objectruleeditor.requested_controls_1e88d011", "requested_controls")])ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.s_saved_inactive_9b19f2f5", "%s: saved, inactive"),Neurotic::Translate(c[Neurotic::UiLiteral("ingame.objectruleeditor.id_1304cb9d", "id")].get<std::string>().c_str()).c_str());if(ImGui::Button(Neurotic::UiLiteral("ingame.objectruleeditor.duplicate_875abe74", "Duplicate"))){auto p=s->profile;auto r=e.draft;r[Neurotic::UiLiteral("ingame.objectruleeditor.id_1304cb9d", "id")]=Id();p[Neurotic::UiLiteral("ingame.objectruleeditor.rules_d4dea7e2", "rules")].push_back(r);auto ack=store.Commit(s->revision,p);e.message=ack.reason;if(ack.accepted){e.dirty=false;e.selected=r[Neurotic::UiLiteral("ingame.objectruleeditor.id_1304cb9d", "id")];}}ImGui::EndTabItem();}ImGui::EndTabBar();}

            auto current=std::find_if(s->rules.begin(),s->rules.end(),[&](const Rule& r){return r.id==e.selected;});if(current!=s->rules.end())ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.detection_s_726e7718", "Detection: %s"),Neurotic::Translate(current->status.c_str()).c_str());ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.effect_inherited_pixel_overrides_unavailable_38a51fd9", "Effect: inherited; pixel overrides unavailable."));}
        ImGui::EndChild();}
    ImGui::TextWrapped(Neurotic::UiLiteral("ingame.objectruleeditor.zu_rules_revision_llu_s_f330fd14", "%zu rules | revision %llu | %s"),s->rules.size(),static_cast<unsigned long long>(s->revision),Neurotic::Translate(e.dirty?Neurotic::UiLiteral("ingame.objectruleeditor.unapplied_edit_c45312dc", "Unapplied edit"):Neurotic::UiLiteral("ingame.objectruleeditor.use_the_host_s_save_settings_to_persist_edits_7295b676", "Use the host's Save Settings to persist edits")).c_str());if(!e.message.empty())ImGui::TextWrapped("%s",Neurotic::Translate(e.message.c_str()).c_str());ImGui::PopID();
}
}
