#pragma once
// Inventory projected directly from Config.h NrOptional fields. No independent setters or defaults.
#include <type_traits>
#include <string>
namespace Neurotic::Semantic::Rules {
template<class T> std::string GlobalValue(const T& v){if constexpr(std::is_same_v<T,bool>)return v?"On":"Off";else if constexpr(std::is_enum_v<T>)return std::to_string(static_cast<int>(v));else if constexpr(std::is_arithmetic_v<T>)return std::to_string(v);else if constexpr(std::is_same_v<T,std::string>)return v;else return "See global settings";}
template<class ConfigT,class Sink> void VisitGlobalControls(const ConfigT& c,Sink&& sink){
    sink("DlssNrEnabled",GlobalValue(c.DlssNrEnabled.value_or_default()));
    sink("DlssNrVulkanPrepare",GlobalValue(c.DlssNrVulkanPrepare.value_or_default()));
    sink("DlssNrAlternateFrame",GlobalValue(c.DlssNrAlternateFrame.value_or_default()));
    sink("DlssNrMultipassEnabled",GlobalValue(c.DlssNrMultipassEnabled.value_or_default()));
    sink("DlssNrExperimentalMode",GlobalValue(c.DlssNrExperimentalMode.value_or_default()));
    sink("DlssNrPreparedDepth",GlobalValue(c.DlssNrPreparedDepth.value_or_default()));
    sink("DlssNrOverrideMultipassGuardrails",GlobalValue(c.DlssNrOverrideMultipassGuardrails.value_or_default()));
    sink("DlssNrOverrideHdrGuardrails",GlobalValue(c.DlssNrOverrideHdrGuardrails.value_or_default()));
    sink("DlssNrOverrideFgGuardrails",GlobalValue(c.DlssNrOverrideFgGuardrails.value_or_default()));
    sink("DlssNrBasicMultipass",GlobalValue(c.DlssNrBasicMultipass.value_or_default()));
    sink("DlssNrSecondLayer",GlobalValue(c.DlssNrSecondLayer.value_or_default()));
    sink("DlssNrSecondLayerWorkingScale",GlobalValue(c.DlssNrSecondLayerWorkingScale.value_or_default()));
    sink("DlssNrSecondLayerScalingDownscaler",GlobalValue(c.DlssNrSecondLayerScalingDownscaler.value_or_default()));
    sink("DlssNrSecondLayerTransfer",GlobalValue(c.DlssNrSecondLayerTransfer.value_or_default()));
    sink("DlssNrSecondLayerPreset",GlobalValue(c.DlssNrSecondLayerPreset.value_or_default()));
    sink("DlssNrSecondLayerIntensity",GlobalValue(c.DlssNrSecondLayerIntensity.value_or_default()));
    sink("DlssNrSecondLayerStyle",GlobalValue(c.DlssNrSecondLayerStyle.value_or_default()));
    sink("DlssNrSecondLayerLocalStructure",GlobalValue(c.DlssNrSecondLayerLocalStructure.value_or_default()));
    sink("DlssNrSecondLayerLocalTone",GlobalValue(c.DlssNrSecondLayerLocalTone.value_or_default()));
    sink("DlssNrSecondLayerSkinStructure",GlobalValue(c.DlssNrSecondLayerSkinStructure.value_or_default()));
    sink("DlssNrSecondLayerAutoMask",GlobalValue(c.DlssNrSecondLayerAutoMask.value_or_default()));
    sink("DlssNrSecondLayerTransferStrength",GlobalValue(c.DlssNrSecondLayerTransferStrength.value_or_default()));
    sink("DlssNrSecondLayerColourStrength",GlobalValue(c.DlssNrSecondLayerColourStrength.value_or_default()));
    sink("DlssNrSecondLayerMaxRatio",GlobalValue(c.DlssNrSecondLayerMaxRatio.value_or_default()));
    sink("DlssNrSecondLayerReversibleMode",GlobalValue(c.DlssNrSecondLayerReversibleMode.value_or_default()));
    sink("DlssNrSecondLayerApplyModel",GlobalValue(c.DlssNrSecondLayerApplyModel.value_or_default()));
    sink("DlssNrRoute",GlobalValue(c.DlssNrRoute.value_or_default()));
    sink("DlssNrPresentInputPolicy",GlobalValue(c.DlssNrPresentInputPolicy.value_or_default()));
    sink("DlssNrNativeProtocol",GlobalValue(c.DlssNrNativeProtocol.value_or_default()));
    sink("DlssNrUiManualResolution",GlobalValue(c.DlssNrUiManualResolution.value_or_default()));
    sink("DlssNrUiManualScale",GlobalValue(c.DlssNrUiManualScale.value_or_default()));
    sink("DlssNrUiPresentManualScale",GlobalValue(c.DlssNrUiPresentManualScale.value_or_default()));
    sink("DlssNrUiEnhancedManualScale",GlobalValue(c.DlssNrUiEnhancedManualScale.value_or_default()));
    sink("DlssNrUiResolutionPreset",GlobalValue(c.DlssNrUiResolutionPreset.value_or_default()));
    sink("DlssNrUiPresentResolutionPreset",GlobalValue(c.DlssNrUiPresentResolutionPreset.value_or_default()));
    sink("DlssNrUiEnhancedResolutionPreset",GlobalValue(c.DlssNrUiEnhancedResolutionPreset.value_or_default()));
    sink("DlssNrUiAfterMethod",GlobalValue(c.DlssNrUiAfterMethod.value_or_default()));
    sink("DlssNrPresentResolution",GlobalValue(c.DlssNrPresentResolution.value_or_default()));
    sink("DlssNrPresentCustomScale",GlobalValue(c.DlssNrPresentCustomScale.value_or_default()));
    sink("DlssNrEnhancedResolution",GlobalValue(c.DlssNrEnhancedResolution.value_or_default()));
    sink("DlssNrEnhancedCustomScale",GlobalValue(c.DlssNrEnhancedCustomScale.value_or_default()));
    sink("DlssNrRunBeforeSr",GlobalValue(c.DlssNrRunBeforeSr.value_or_default()));
    sink("DlssNrRenderingMode",GlobalValue(c.DlssNrRenderingMode.value_or_default()));
    sink("DlssNrPreDlaa",GlobalValue(c.DlssNrPreDlaa.value_or_default()));
    sink("DlssNrPreSrSoftReset",GlobalValue(c.DlssNrPreSrSoftReset.value_or_default()));
    sink("DlssNrToggleKey",GlobalValue(c.DlssNrToggleKey.value_or_default()));
    sink("DlssNrPreset",GlobalValue(c.DlssNrPreset.value_or_default()));
    sink("DlssNrIntensity",GlobalValue(c.DlssNrIntensity.value_or_default()));
    sink("DlssNrStyle",GlobalValue(c.DlssNrStyle.value_or_default()));
    sink("DlssNrLocalStructure",GlobalValue(c.DlssNrLocalStructure.value_or_default()));
    sink("DlssNrLocalTone",GlobalValue(c.DlssNrLocalTone.value_or_default()));
    sink("DlssNrSkinStructure",GlobalValue(c.DlssNrSkinStructure.value_or_default()));
    sink("DlssNrAutoMask",GlobalValue(c.DlssNrAutoMask.value_or_default()));
    sink("DlssNrTransferStrength",GlobalValue(c.DlssNrTransferStrength.value_or_default()));
    sink("DlssNrColourStrength",GlobalValue(c.DlssNrColourStrength.value_or_default()));
    sink("DlssNrReversibleMode",GlobalValue(c.DlssNrReversibleMode.value_or_default()));
    sink("DlssNrApplyModel",GlobalValue(c.DlssNrApplyModel.value_or_default()));
    sink("DlssNrHoldFrame",GlobalValue(c.DlssNrHoldFrame.value_or_default()));
    sink("DlssNrMaxRatio",GlobalValue(c.DlssNrMaxRatio.value_or_default()));
    sink("DlssNrTransfer",GlobalValue(c.DlssNrTransfer.value_or_default()));
    sink("DlssNrWhitePointFromExposure",GlobalValue(c.DlssNrWhitePointFromExposure.value_or_default()));
    sink("DlssNrProbeD3D11",GlobalValue(c.DlssNrProbeD3D11.value_or_default()));
    sink("DlssNrDebugView",GlobalValue(c.DlssNrDebugView.value_or_default()));
    sink("DlssNrCompare",GlobalValue(c.DlssNrCompare.value_or_default()));
    sink("DlssNrCompareSplit",GlobalValue(c.DlssNrCompareSplit.value_or_default()));
    sink("DlssNrCompareZoom",GlobalValue(c.DlssNrCompareZoom.value_or_default()));
    sink("DlssNrCompareSwap",GlobalValue(c.DlssNrCompareSwap.value_or_default()));
    sink("DlssNrCompareTags",GlobalValue(c.DlssNrCompareTags.value_or_default()));
    sink("DlssNrTagScale",GlobalValue(c.DlssNrTagScale.value_or_default()));
    sink("DlssNrWorkingScale",GlobalValue(c.DlssNrWorkingScale.value_or_default()));
    sink("DlssNrScalingDownscaler",GlobalValue(c.DlssNrScalingDownscaler.value_or_default()));
    sink("DlssNrProxyProbe",GlobalValue(c.DlssNrProxyProbe.value_or_default()));
    sink("DlssNrUseProxy",GlobalValue(c.DlssNrUseProxy.value_or_default()));
    sink("DlssNrScanExposure",GlobalValue(c.DlssNrScanExposure.value_or_default()));
    sink("DlssNrWhitePointSource",GlobalValue(c.DlssNrWhitePointSource.value_or_default()));
    sink("DlssNrScanMeter",GlobalValue(c.DlssNrScanMeter.value_or_default()));
    sink("DlssNrScanAnchorValue",GlobalValue(c.DlssNrScanAnchorValue.value_or_default()));
    sink("DlssNrScanAnchorWhitePoint",GlobalValue(c.DlssNrScanAnchorWhitePoint.value_or_default()));
    sink("DlssNrScanAnchors",GlobalValue(c.DlssNrScanAnchors.value_or_default()));
    sink("DlssNrScanInverted",GlobalValue(c.DlssNrScanInverted.value_or_default()));
    sink("DlssNrWhitePointTrim",GlobalValue(c.DlssNrWhitePointTrim.value_or_default()));
    sink("DlssNrScanTrim",GlobalValue(c.DlssNrScanTrim.value_or_default()));
    sink("DlssNrPasses",GlobalValue(c.DlssNrPasses.value_or_default()));
    sink("DlssNrAutoCapture",GlobalValue(c.DlssNrAutoCapture.value_or_default()));
    sink("DlssNrWhitePointScale",GlobalValue(c.DlssNrWhitePointScale.value_or_default()));
}
}
