#include "Dav2Host.h"
#include "Dav2Module.h"
#include "Dav2EngineCache.h"
#include "Dav2InteropDx12.h"
#include <d3d11_4.h>
#include <d3dcompiler.h>
#include <bit>
#include "PrepareInput.h"
#include "MaterializeDepth.h"
#include "EstimateRange.h"
namespace nrw::depth {
namespace {
struct Handle {HANDLE value=nullptr;~Handle(){if(value)CloseHandle(value);}Handle()=default;Handle(const Handle&)=delete;};
FrameKey Key(const CapturedFrame& f,uint64_t source){return {source,f.stamp.streamEpoch,f.stamp.sequence,f.stamp.geometryEpoch,f.stamp.configEpoch};}
bool SameEpochs(const FrameKey& a,const FrameKey& b){return a.sourceId==b.sourceId&&a.streamEpoch==b.streamEpoch&&a.geometryEpoch==b.geometryEpoch&&a.configEpoch==b.configEpoch;}
}
struct Dav2Host::Impl {
 Settings settings;bool ready=false,quarantined=false,stopping=false;std::string reason;
 std::unique_ptr<Dav2EngineCache> cache;std::unique_ptr<Dav2Module> module;void* backend=nullptr;
 ComPtr<ID3D11Device> d11;ComPtr<ID3D11Device5> d115;ComPtr<ID3D11DeviceContext> c11;ComPtr<ID3D11DeviceContext4> c114;
 ComPtr<ID3D12Device> d12;ComPtr<ID3D12CommandQueue> queue;ComPtr<ID3D12CommandAllocator> allocator;ComPtr<ID3D12GraphicsCommandList> list;
 ComPtr<ID3D11Fence> ingress11;ComPtr<ID3D12Fence> ingress12,prepared,output,done;
 Handle inputHandle,outputHandle,preparedHandle,outputFenceHandle;uint64_t ingressValue=0,preparedValue=0,outputValue=0,doneValue=0,previewValue=0;
 ComPtr<ID3D12Resource> inputTensor,outputTensor,rangeInitializationUpload,previousRange,nextRange,rangeReadback,source12,raw12,validity12;
 ComPtr<ID3D11Texture2D> source11,raw11,validity11,preview11;
 ComPtr<ID3D11ShaderResourceView> rawView,validityView;ComPtr<ID3D11VertexShader> vertex;ComPtr<ID3D11PixelShader> pixel;ComPtr<ID3D11Buffer> previewConstants;
 ComputeKernel prepare,materialize,range;
 enum class Phase {Idle,Inference,Materialize,Preview};Phase phase=Phase::Idle;
 bool rangeInitialized=false;JobQueue jobs;FreshCounter fresh;std::optional<CapturedFrame> pending,active;FrameKey current{},latest{},previous{};float low=0,high=0;bool rangeValid=false;uint64_t nextStart=0;
 unsigned Width()const{return 518;}unsigned Height()const{return settings.profile==Profile::Reference?518:294;}
 void Setup(ID3D11Device* device,ID3D11DeviceContext* context,const std::filesystem::path& root){
  cache=std::make_unique<Dav2EngineCache>();if(!cache->Open(root,Width(),Height(),reason))throw std::runtime_error(reason);
  module=std::make_unique<Dav2Module>();if(!module->Open(cache->Root(),reason))throw std::runtime_error(reason);
  d11=device;c11=context;ComPtr<ID3D11Device> parent;c11->GetDevice(&parent);if(parent.Get()!=d11.Get()||c11->GetType()!=D3D11_DEVICE_CONTEXT_IMMEDIATE)throw std::runtime_error("Depth requires capture immediate context");
  DxCheck(d11.As(&d115),"Depth D11 fence device");DxCheck(c11.As(&c114),"Depth D11 fence context");ComPtr<IDXGIDevice> dxgi;ComPtr<IDXGIAdapter> adapter;DxCheck(d11.As(&dxgi),"Depth capture DXGI device");DxCheck(dxgi->GetAdapter(&adapter),"Depth capture adapter");DXGI_ADAPTER_DESC adapterDesc{};DxCheck(adapter->GetDesc(&adapterDesc),"Depth capture adapter identity");
  if(adapterDesc.VendorId!=0x10de)throw std::runtime_error("Depth Anything TensorRT requires an NVIDIA capture adapter");
  DxCheck(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&d12)),"Depth same-adapter D12 device");D3D12_COMMAND_QUEUE_DESC q{};q.Type=D3D12_COMMAND_LIST_TYPE_DIRECT;DxCheck(d12->CreateCommandQueue(&q,IID_PPV_ARGS(&queue)),"Depth private queue");DxCheck(d12->CreateCommandAllocator(q.Type,IID_PPV_ARGS(&allocator)),"Depth allocator");DxCheck(d12->CreateCommandList(0,q.Type,allocator.Get(),nullptr,IID_PPV_ARGS(&list)),"Depth list");DxCheck(list->Close(),"Depth initial close");
  DxCheck(d115->CreateFence(0,D3D11_FENCE_FLAG_SHARED,IID_PPV_ARGS(&ingress11)),"Depth ingress fence");Handle ingressHandle;DxCheck(ingress11->CreateSharedHandle(nullptr,GENERIC_ALL,nullptr,&ingressHandle.value),"Share depth ingress fence");DxCheck(d12->OpenSharedHandle(ingressHandle.value,IID_PPV_ARGS(&ingress12)),"Import depth ingress fence");
  DxCheck(d12->CreateFence(0,D3D12_FENCE_FLAG_SHARED,IID_PPV_ARGS(&prepared)),"Depth preparation fence");DxCheck(d12->CreateFence(0,D3D12_FENCE_FLAG_SHARED,IID_PPV_ARGS(&output)),"Depth output fence");DxCheck(d12->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&done)),"Depth host completion fence");DxCheck(d12->CreateSharedHandle(prepared.Get(),nullptr,GENERIC_ALL,nullptr,&preparedHandle.value),"Share depth prepared fence");DxCheck(d12->CreateSharedHandle(output.Get(),nullptr,GENERIC_ALL,nullptr,&outputFenceHandle.value),"Share depth output fence");
  const uint64_t count=uint64_t(Width())*Height();inputTensor=Buffer(d12.Get(),count*12,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS,D3D12_HEAP_FLAG_SHARED);outputTensor=Buffer(d12.Get(),count*4,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS,D3D12_HEAP_FLAG_SHARED);
  DxCheck(d12->CreateSharedHandle(inputTensor.Get(),nullptr,GENERIC_ALL,nullptr,&inputHandle.value),"Share depth input tensor");DxCheck(d12->CreateSharedHandle(outputTensor.Get(),nullptr,GENERIC_ALL,nullptr,&outputHandle.value),"Share depth output tensor");
  previousRange=Buffer(d12.Get(),257*16,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);nextRange=Buffer(d12.Get(),257*16,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);rangeReadback=Buffer(d12.Get(),16,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);
  rangeInitializationUpload=Buffer(d12.Get(),257*16,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);void* initialRange=nullptr;DxCheck(rangeInitializationUpload->Map(0,nullptr,&initialRange),"Initialize depth range history");std::memset(initialRange,0,257*16);rangeInitializationUpload->Unmap(0,nullptr);
  prepare.Create(d12.Get(),Dav2PrepareInput,sizeof(Dav2PrepareInput));prepare.BufferUav(d12.Get(),0,inputTensor.Get(),uint32_t(count*3));materialize.Create(d12.Get(),Dav2MaterializeDepth,sizeof(Dav2MaterializeDepth));materialize.BufferSrv(d12.Get(),0,outputTensor.Get(),uint32_t(count));range.Create(d12.Get(),Dav2EstimateRange,sizeof(Dav2EstimateRange));range.BufferSrv(d12.Get(),0,outputTensor.Get(),uint32_t(count));range.BufferSrv(d12.Get(),1,previousRange.Get(),257,true);range.BufferUav(d12.Get(),0,nextRange.Get(),257,true);
  constexpr char previewShader[]="Texture2D<float> raw:register(t0); Texture2D<float> valid:register(t1); cbuffer Range:register(b0){float low,high,rangeValid,unused;} float4 VS(uint id:SV_VertexID):SV_Position{float2 uv=float2((id<<1)&2,id&2);return float4(uv*float2(2,-2)+float2(-1,1),0,1);} float4 PS(float4 p:SV_Position):SV_Target{int3 q=int3(int2(p.xy),0);float d=raw.Load(q);if(valid.Load(q)<.5||!isfinite(d)||d<0)return float4(1,0,1,1);float t=rangeValid>0?saturate((d-low)/(high-low)):.5;return float4(saturate(1.5-abs(4*t-float3(3,2,1))),1);}";
  ComPtr<ID3DBlob> vs,ps,error;DxCheck(D3DCompile(previewShader,sizeof(previewShader)-1,nullptr,nullptr,nullptr,"VS","vs_5_0",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&vs,&error),"Depth preview vertex shader");DxCheck(D3DCompile(previewShader,sizeof(previewShader)-1,nullptr,nullptr,nullptr,"PS","ps_5_0",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&ps,&error),"Depth preview pixel shader");DxCheck(d11->CreateVertexShader(vs->GetBufferPointer(),vs->GetBufferSize(),nullptr,&vertex),"Depth preview vertex");DxCheck(d11->CreatePixelShader(ps->GetBufferPointer(),ps->GetBufferSize(),nullptr,&pixel),"Depth preview pixel");D3D11_BUFFER_DESC cb{};cb.ByteWidth=16;cb.Usage=D3D11_USAGE_DEFAULT;cb.BindFlags=D3D11_BIND_CONSTANT_BUFFER;DxCheck(d11->CreateBuffer(&cb,nullptr,&previewConstants),"Depth preview constants");
  BackendCreate c;c.engine=cache->Engine().data();c.engineBytes=cache->Engine().size();c.width=Width();c.height=Height();c.adapter=adapterDesc.AdapterLuid;c.identity=cache->Identity();c.runtimeRoot=cache->Root().c_str();c.input=inputHandle.value;c.output=outputHandle.value;c.preparedFence=preparedHandle.value;c.outputFence=outputFenceHandle.value;c.inputBytes=count*12;c.outputBytes=count*4;auto inputDesc=inputTensor->GetDesc(),outputDesc=outputTensor->GetDesc();c.inputAllocation=d12->GetResourceAllocationInfo(0,1,&inputDesc).SizeInBytes;c.outputAllocation=d12->GetResourceAllocationInfo(0,1,&outputDesc).SizeInBytes;
  char errorText[2048]{};backend=module->Api()->create(&c,errorText,sizeof(errorText));if(!backend)throw std::runtime_error(errorText[0]?errorText:"Depth CUDA/TensorRT generation unavailable");if(module->Api()->poll(backend,errorText,sizeof(errorText))==BackendPoll::Faulted){quarantined=true;throw std::runtime_error(errorText[0]?errorText:"Depth initialization completion uncertain; restart worker required");}ready=true;reason="Depth Anything V2 Small TensorRT ready; estimated relative depth; NR adapter unqualified";
 }
 void SharedImage(unsigned w,unsigned h,DXGI_FORMAT format,unsigned flags,ComPtr<ID3D11Texture2D>& image11,ComPtr<ID3D12Resource>& image12){
  image12.Reset();image11.Reset();D3D11_TEXTURE2D_DESC d{};d.Width=w;d.Height=h;d.MipLevels=d.ArraySize=1;d.Format=format;d.SampleDesc.Count=1;d.Usage=D3D11_USAGE_DEFAULT;d.BindFlags=flags;d.MiscFlags=D3D11_RESOURCE_MISC_SHARED_NTHANDLE;DxCheck(d11->CreateTexture2D(&d,nullptr,&image11),"Depth shared image");ComPtr<IDXGIResource1> resource;DxCheck(image11.As(&resource),"Depth image sharing interface");Handle handle;DxCheck(resource->CreateSharedHandle(nullptr,DXGI_SHARED_RESOURCE_READ|DXGI_SHARED_RESOURCE_WRITE,nullptr,&handle.value),"Depth image NT handle");DxCheck(d12->OpenSharedHandle(handle.value,IID_PPV_ARGS(&image12)),"Import actual depth image");
 }
 void Begin(){
  if(stopping||phase!=Phase::Idle||!pending)return;LARGE_INTEGER now{};QueryPerformanceCounter(&now);if(uint64_t(now.QuadPart)<nextStart)return;nextStart=uint64_t(now.QuadPart)+uint64_t(frequency/settings.hz);const auto key=jobs.Begin();if(!key)return;active=std::move(pending);pending.reset();current=*key;const auto& f=*active;
  D3D11_TEXTURE2D_DESC desc{};f.texture->GetDesc(&desc);ComPtr<ID3D11Device> parent;f.texture->GetDevice(&parent);if(desc.Width>3840||desc.Height>2160)throw std::runtime_error("Depth capture exceeds the bounded 3840 x 2160 profile; image-only NR remains available");if(parent.Get()!=d11.Get()||desc.Width!=f.stamp.width||desc.Height!=f.stamp.height||desc.Format!=DXGI_FORMAT_B8G8R8A8_UNORM||desc.SampleDesc.Count!=1||desc.MipLevels!=1||desc.ArraySize!=1)throw std::runtime_error("Depth capture texture/stamp/device mismatch");
  SharedImage(desc.Width,desc.Height,desc.Format,D3D11_BIND_SHADER_RESOURCE,source11,source12);SharedImage(desc.Width,desc.Height,DXGI_FORMAT_R32_FLOAT,D3D11_BIND_SHADER_RESOURCE|D3D11_BIND_UNORDERED_ACCESS,raw11,raw12);SharedImage(desc.Width,desc.Height,DXGI_FORMAT_R32_FLOAT,D3D11_BIND_SHADER_RESOURCE|D3D11_BIND_UNORDERED_ACCESS,validity11,validity12);
  rawView.Reset();validityView.Reset();DxCheck(d11->CreateShaderResourceView(raw11.Get(),nullptr,&rawView),"Depth raw preview view");DxCheck(d11->CreateShaderResourceView(validity11.Get(),nullptr,&validityView),"Depth validity preview view");prepare.TextureSrv(d12.Get(),0,source12.Get(),desc.Format);materialize.TextureUav(d12.Get(),0,raw12.Get());materialize.TextureUav(d12.Get(),1,validity12.Get());
  auto box=MakeLetterbox(desc.Width,desc.Height,Width(),Height());DxCheck(allocator->Reset(),"Depth prepare allocator reset");DxCheck(list->Reset(allocator.Get(),nullptr),"Depth prepare list reset");if(!rangeInitialized){Transition(list.Get(),previousRange.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_DEST);list->CopyResource(previousRange.Get(),rangeInitializationUpload.Get());Transition(list.Get(),previousRange.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);rangeInitialized=true;}Transition(list.Get(),source12.Get(),D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);Transition(list.Get(),inputTensor.Get(),D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);prepare.Dispatch(list.Get(),{desc.Width,desc.Height,Width(),Height(),box.contentWidth,box.contentHeight,box.left,box.top,0,0,0,0},(Width()+7)/8,(Height()+7)/8);Transition(list.Get(),inputTensor.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COMMON);Transition(list.Get(),source12.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COMMON);DxCheck(list->Close(),"Depth prepare close");
  quarantined=true; // Failure after a possible copy/submission must retain the entire generation.
  c11->CopyResource(source11.Get(),f.texture.Get());DxCheck(c114->Signal(ingress11.Get(),++ingressValue),"Depth ingress signal");c11->Flush();DxCheck(queue->Wait(ingress12.Get(),ingressValue),"Depth ingress wait");ID3D12CommandList* lists[]{list.Get()};queue->ExecuteCommandLists(1,lists);DxCheck(queue->Signal(prepared.Get(),++preparedValue),"Depth prepared signal");
  char errorText[2048]{};if(!module->Api()->submit(backend,preparedValue,++outputValue,errorText,sizeof(errorText)))throw std::runtime_error(errorText[0]?errorText:"Depth enqueue/output signal failed");quarantined=false;phase=Phase::Inference;
 }
 bool FenceComplete(ID3D12Fence* f,uint64_t value){const auto completed=f->GetCompletedValue();if(completed==UINT64_MAX)throw std::runtime_error("Depth GPU removed; completion unknown");return completed>=value;}
 void Materialize(){
  // Never queue an output wait before the CUDA event after its external signal has completed.
  if(!FenceComplete(output.Get(),outputValue)||!FenceComplete(prepared.Get(),preparedValue))throw std::runtime_error("Depth outer event completed without its actual external fence values");
  DxCheck(allocator->Reset(),"Depth postprocess allocator reset");DxCheck(list->Reset(allocator.Get(),nullptr),"Depth postprocess list reset");auto box=MakeLetterbox(active->stamp.width,active->stamp.height,Width(),Height());
  Transition(list.Get(),outputTensor.Get(),D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);Transition(list.Get(),raw12.Get(),D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);Transition(list.Get(),validity12.Get(),D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
  materialize.Dispatch(list.Get(),{Width(),Height(),box.contentWidth,box.contentHeight,box.left,box.top,active->stamp.width,active->stamp.height,0,0,0,0},(active->stamp.width+7)/8,(active->stamp.height+7)/8);
  Transition(list.Get(),source12.Get(),D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);range.TextureSrv(d12.Get(),2,source12.Get(),DXGI_FORMAT_B8G8R8A8_UNORM);
  const float delta=previous.Valid()&&active->stamp.timestampQpc>previousTimestamp?float(double(active->stamp.timestampQpc-previousTimestamp)/frequency):0;range.Dispatch(list.Get(),{Width(),box.contentWidth,box.contentHeight,box.left,box.top,uint32_t(active->stamp.reset||!SameEpochs(previous,current)),active->stamp.width,active->stamp.height,std::bit_cast<uint32_t>(delta),std::bit_cast<uint32_t>(.25f),0,0},1);
  Transition(list.Get(),nextRange.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);Transition(list.Get(),previousRange.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_DEST);list->CopyBufferRegion(rangeReadback.Get(),0,nextRange.Get(),0,16);list->CopyResource(previousRange.Get(),nextRange.Get());Transition(list.Get(),source12.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COMMON);Transition(list.Get(),nextRange.Get(),D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);Transition(list.Get(),previousRange.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);Transition(list.Get(),outputTensor.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COMMON);Transition(list.Get(),raw12.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COMMON);Transition(list.Get(),validity12.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COMMON);DxCheck(list->Close(),"Depth postprocess close");
  quarantined=true;DxCheck(queue->Wait(output.Get(),outputValue),"Depth observed output wait");ID3D12CommandList* lists[]{list.Get()};queue->ExecuteCommandLists(1,lists);DxCheck(queue->Signal(done.Get(),++doneValue),"Depth postprocess signal");quarantined=false;phase=Phase::Materialize;
 }
 uint64_t previousTimestamp=0;double frequency=1;
 void Preview(){
  void* data=nullptr;D3D12_RANGE read{0,16};DxCheck(rangeReadback->Map(0,&read,&data),"Depth metadata readback");auto v=static_cast<float*>(data);low=v[0];high=v[1];rangeValid=v[2]>0&&NormalizeRelative(low,low,high).valid;D3D12_RANGE none{0,0};rangeReadback->Unmap(0,&none);
  preview11.Reset();D3D11_TEXTURE2D_DESC d{};d.Width=active->stamp.width;d.Height=active->stamp.height;d.MipLevels=d.ArraySize=1;d.Format=DXGI_FORMAT_B8G8R8A8_UNORM;d.SampleDesc.Count=1;d.BindFlags=D3D11_BIND_RENDER_TARGET|D3D11_BIND_SHADER_RESOURCE;DxCheck(d11->CreateTexture2D(&d,nullptr,&preview11),"Depth owned preview texture");ComPtr<ID3D11RenderTargetView> target;DxCheck(d11->CreateRenderTargetView(preview11.Get(),nullptr,&target),"Depth preview target");
  const float constants[]{low,high,rangeValid?1.f:0.f,0};quarantined=true;c11->ClearState();c11->UpdateSubresource(previewConstants.Get(),0,nullptr,constants,0,0);auto* buffer=previewConstants.Get();auto* rtv=target.Get();ID3D11ShaderResourceView* views[]{rawView.Get(),validityView.Get()};c11->OMSetRenderTargets(1,&rtv,nullptr);c11->PSSetShaderResources(0,2,views);c11->PSSetConstantBuffers(0,1,&buffer);c11->VSSetShader(vertex.Get(),nullptr,0);c11->PSSetShader(pixel.Get(),nullptr,0);c11->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);D3D11_VIEWPORT viewport{0,0,float(d.Width),float(d.Height),0,1};c11->RSSetViewports(1,&viewport);c11->Draw(3,0);c11->ClearState();previewValue=++ingressValue;DxCheck(c114->Signal(ingress11.Get(),previewValue),"Depth preview completion signal");c11->Flush();quarantined=false;phase=Phase::Preview;
 }
 std::optional<DepthFrame> Poll(){
  if(!ready||quarantined)return {};
  if(phase==Phase::Idle){Begin();return {};}
  if(phase==Phase::Inference){char error[2048]{};const auto result=module->Api()->poll(backend,error,sizeof(error));if(result==BackendPoll::Faulted)throw std::runtime_error(error[0]?error:"Depth outer completion faulted");if(result!=BackendPoll::Complete)return {};Materialize();return {};}
  if(phase==Phase::Materialize){if(!FenceComplete(done.Get(),doneValue))return {};Preview();return {};}
  const auto completed=ingress11->GetCompletedValue();if(completed==UINT64_MAX)throw std::runtime_error("Depth preview completion unknown");if(completed<previewValue)return {};
  DepthFrame result;result.color=*active;result.color.pairedDepthOutput=true;result.receipt={current,Encoding::EstimatedRelativeRaw,true,false};result.raw=raw11;result.validity=validity11;result.preview=preview11;result.low=low;result.high=high;result.rangeValid=rangeValid;result.reason=rangeValid?"Estimated relative depth preview; range uses sampled percentiles; NR adapter unqualified":"Estimated relative depth preview; flat/invalid normalization range; NR adapter refused";
  // The validity texture is authoritative per pixel. Sampled range is never full-image validation/confidence.
  previous=current;previousTimestamp=active->stamp.timestampQpc;LARGE_INTEGER publicationTime{};QueryPerformanceCounter(&publicationTime);const bool publish=!stopping&&SameEpochs(current,latest)&&PublicationFresh(active->stamp.timestampQpc,uint64_t(publicationTime.QuadPart),uint64_t(frequency));if(publish)fresh.Record(current);jobs.Finish(current);active.reset();phase=Phase::Idle;if(publish)return result;return {};
 }
};
Dav2Host::Dav2Host():impl_(std::make_unique<Impl>()){}
Dav2Host::~Dav2Host(){Stop();if(impl_->quarantined)impl_.release();}
bool Dav2Host::Initialize(ID3D11Device* device,ID3D11DeviceContext* context,const Settings& settings,const std::filesystem::path& root,std::string& reason){Stop();if(impl_->quarantined){reason="Depth generation retained; restart worker required";return false;}impl_=std::make_unique<Impl>();auto& p=*impl_;p.settings=settings;try{if(!ValidSettings(settings)||settings.provider!=Provider::Dav2||!device||!context)throw std::runtime_error("Depth settings/device unavailable");LARGE_INTEGER f{};QueryPerformanceFrequency(&f);p.frequency=double(f.QuadPart);p.Setup(device,context,root);reason=p.reason;return true;}catch(const std::exception& e){p.reason=reason=e.what();return false;}}
void Dav2Host::Offer(const CapturedFrame& frame,uint64_t sourceId){auto& p=*impl_;if(!p.ready||p.stopping||p.quarantined||!frame.texture)return;const auto key=Key(frame,sourceId);p.latest=key;if(p.jobs.Offer(key))p.pending=frame;}
void Dav2Host::ObserveEpochs(const FrameKey& key){auto& p=*impl_;if(!SameEpochs(p.latest,key)){p.latest=key;p.pending.reset();p.jobs.DiscardPending();}}
std::optional<DepthFrame> Dav2Host::Poll(std::string& reason){auto& p=*impl_;try{auto r=p.Poll();reason=p.reason;return r;}catch(const std::exception& e){if(p.phase==Impl::Phase::Idle&&!p.quarantined){p.ready=false;if(p.jobs.Active())p.jobs.Finish(*p.jobs.Active());p.active.reset();p.pending.reset();}else p.quarantined=true;p.reason=reason=e.what();return {};}}
void Dav2Host::Stop(){auto& p=*impl_;p.stopping=true;p.jobs.Invalidate();p.pending.reset();const auto start=GetTickCount64();while(p.ready&&!p.quarantined&&p.phase!=Impl::Phase::Idle){std::string ignored;Poll(ignored);if(GetTickCount64()-start>=5000){p.quarantined=true;p.reason="Depth retirement timed out; GPU generation retained";break;}Sleep(1);}if(p.quarantined)return;if(p.backend&&p.module&&!p.module->Api()->close(p.backend)){p.quarantined=true;return;}p.backend=nullptr;p.ready=false;}
bool Dav2Host::Busy()const{return impl_->ready&&!impl_->quarantined&&(impl_->phase!=Impl::Phase::Idle||impl_->pending.has_value());}
bool Dav2Host::RequiresRestart()const{return impl_->quarantined;}bool Dav2Host::Ready()const{return impl_->ready&&!impl_->quarantined;}uint64_t Dav2Host::Fresh()const{return impl_->fresh.Count();}uint64_t Dav2Host::Dropped()const{return impl_->jobs.Dropped();}
}
