#include "ui/HubViewModel.h"
#include "imgui.h"
#include "imgui_internal.h"
#include "../../OptiScaler/menu/font/Hack_Compressed.h"
#include <iostream>
#include <fstream>
#include "NativeInstallerPackageFixture.h"
namespace {
void Feed(nh::HubModel& model,const std::filesystem::path& receipt,const nh::Json& result){
 std::ofstream(receipt)<<result.dump();wchar_t system[MAX_PATH];GetSystemDirectoryW(system,MAX_PATH);auto exe=std::filesystem::path(system)/L"cmd.exe";auto command=nh::Quote(exe.wstring())+L" /d /c exit 0";
 STARTUPINFOW start{sizeof(start)};PROCESS_INFORMATION child{};if(!CreateProcessW(exe.c_str(),command.data(),nullptr,nullptr,FALSE,CREATE_NO_WINDOW,nullptr,nullptr,&start,&child))throw std::runtime_error("Issue fixture could not start");CloseHandle(child.hThread);WaitForSingleObject(child.hProcess,5000);
 model.installer.process=child.hProcess;model.installer.result=receipt;model.installer.busy=true;model.Poll();
}
}
int RunFifthPassTests() try{
 int failed=0;auto check=[&](bool ok,const char* label){std::cout<<(ok?"PASS ":"FAIL ")<<label<<'\n';if(!ok)++failed;};
 auto fixture=nh::UserRoot()/L"fifth-pass";std::filesystem::create_directories(fixture/L"empty");auto path=nh::Utf8((fixture/L"empty").wstring());
 nh::HubModel model;model.games.push_back({"old","Existing Steam game","Steam","C:/fixture/old",{}});model.page=0;model.AddDirectory(fixture/L"empty");auto until=GetTickCount64()+10000;while(model.discovery.busy&&GetTickCount64()<until){model.Poll();Sleep(1);}
 check(!model.discovery.busy&&model.lastResult.value("kind","")=="DiscoveryResult"&&model.lastResult["games"].empty()&&model.lastResult["directories"].size()==1&&model.lastResult["directories"][0]["path"]==path&&model.games.size()==1&&model.page==0,"NH-HOME-ADD: empty directory scans only itself, preserves games and stays on Home");
 if(model.discovery.busy){model.CancelScan();while(model.discovery.busy){model.Poll();Sleep(1);}}
 std::filesystem::create_directories(fixture/L"emptyExtra");model.knownDirectories={{path,"Steam",true},{path+"Extra","GOG",true}};auto entries=model.SearchDirectories();check(entries.size()==2&&entries[0].automatic&&entries[0].source=="Steam","NH-DIRECTORIES: canonical dedup retains automatic provenance");
 model.RemoveDirectory(0);entries=model.SearchDirectories();check(model.searchRoots.empty()&&model.excludedRoots.size()==1&&entries.size()==1&&entries[0].path==path+"Extra"&&model.games.size()==1,"NH-DIRECTORIES: removal excludes future scans without removing games or prefix siblings");
 model.Save();nh::HubModel loaded;loaded.Load();until=GetTickCount64()+15000;while(loaded.readiness.busy&&GetTickCount64()<until){loaded.Poll();Sleep(1);}auto readinessRequest=loaded.readiness.request;auto snapshot=loaded.preflight;
 for(int frame=0;frame<300;frame++)loaded.Poll();check(!loaded.readiness.busy&&loaded.readiness.request==readinessRequest&&loaded.preflight==snapshot,"NH-PREFLIGHT: idle polling does not schedule another check");check(loaded.excludedRoots==model.excludedRoots&&loaded.SearchDirectories().size()==1,"NH-DIRECTORIES: exclusions and directory metadata persist");
 {nh::HubModel favorites;favorites.games={{"beta","Beta","Manual",path,{}},{"zebra","Zebra","Steam",path+"/z",{}},{"alpha","alpha","Manual",path+"/a",{}}};favorites.ToggleFavorite(1);check(favorites.OrderedGames()==std::vector<int>({2,0,1}),"NH-FAVORITES: All remains alphabetical including manual games");favorites.favoritesFirst=true;favorites.Save();check(favorites.OrderedGames()==std::vector<int>({1,2,0})&&favorites.OrderedGames("bet")==std::vector<int>({0}),"NH-FAVORITES: favorites sort first and remaining games stay visible/alphabetical");nh::HubModel restored;restored.Load();check(restored.favoritesFirst&&restored.games.size()==3&&restored.games[1].favorite,"NH-FAVORITES: star and ordering preference persist across app reload");auto deadline=GetTickCount64()+15000;while(restored.readiness.busy&&GetTickCount64()<deadline){restored.Poll();Sleep(1);}} wchar_t system[MAX_PATH];GetSystemDirectoryW(system,MAX_PATH);auto exe=nh::Utf8((std::filesystem::path(system)/L"cmd.exe").wstring()),root=nh::Utf8(system);nh::HubModel catalog;nh::Game game{"steam-fixture","Steam identity","Steam",root,nh::InspectExecutable(std::filesystem::path(system)/L"cmd.exe")};game.storeId="730";game.steamRoot="C:/fixture/Steam";catalog.games.push_back(game);catalog.games[0].favorite=true;catalog.scanFolder=root;
 auto receipt=nh::Json{{"protocolVersion",2},{"kind","DiscoveryResult"},{"errors",nh::Json::array()},{"directories",nh::Json::array({{{"path",root},{"source","Custom"},{"automatic",false}}})},{"games",nh::Json::array({{{"id","custom"},{"title","cmd"},{"store","Custom"},{"installRoot",root},{"executable",exe}}})}};
 catalog.MergeDiscovery(receipt);check(catalog.games.size()==1&&catalog.games[0].id==game.id&&catalog.games[0].storeId=="730"&&catalog.games[0].steamRoot==game.steamRoot&&catalog.games[0].favorite,"NH-FOLDER-MERGE: folder rescan preserves launcher identity and Steam artwork");
 catalog.knownDirectories={{root,"Steam",true}};catalog.MergeDiscovery(receipt);check(catalog.knownDirectories.size()==1&&catalog.knownDirectories[0].automatic&&catalog.knownDirectories[0].source=="Steam","NH-FOLDER-MERGE: automatic directory provenance survives a folder-only rescan");
 auto before=catalog.games;receipt["directories"][0]["path"]="C:/elsewhere";bool rejected=false;try{catalog.MergeDiscovery(receipt);}catch(...){rejected=true;}check(rejected&&catalog.games[0].id==before[0].id,"NH-FOLDER-MERGE: cross-folder metadata rejected atomically");
 nh::HubModel issue;issue.games={game};issue.selected=0;Feed(issue,fixture/L"issue.json",{{"status","NeedsDecision"},{"decisionKind","ManagedConflict"},{"target",exe},{"recordedProxy","winmm.dll"},{"conflicts",nh::Json::array({"winmm.dll"})},{"reason","Preserved"}});
 check(issue.showIssue&&issue.operationIssue["conflicts"][0]=="winmm.dll"&&issue.inspection.is_null(),"NH-RECOVERY-UI: modified-file refusal exposes target-specific recovery explanation");
 auto riskRoot=fixture/L"risk";std::filesystem::create_directories(riskRoot);auto riskExe=riskRoot/L"cs2.exe";std::filesystem::copy_file(std::filesystem::path(system)/L"cmd.exe",riskExe,std::filesystem::copy_options::overwrite_existing);auto exeTime=std::filesystem::last_write_time(riskExe);
 nh::test::NativeInstallerPackageFixture packageFixture(fixture);
 nh::HubModel risk;nh::Game riskGame{"risk","Candidate","Manual",nh::Utf8(riskRoot.wstring()),nh::InspectExecutable(riskExe)};risk.games={riskGame};risk.selected=0;risk.continueWithoutRuntime=true;
 // This inert executable has no proxy profile. Choose its fixture proxy so
 // these scenarios exercise anti-cheat consent after the proxy decision.
 risk.ChooseProxy(0);risk.Plan("Install");
 // An Execute completion can immediately start a separate Inspect. Wait for
 // both helpers; a slow fixture must not race StartInstaller with that refresh.
 auto wait=[&]{auto end=GetTickCount64()+120000;while(risk.installer.busy&&GetTickCount64()<end){risk.Poll();Sleep(2);}if(risk.installer.busy)throw std::runtime_error("Anti-cheat fixture helper did not finish within 120 seconds");};wait();
 check(risk.showIssue&&risk.operationIssue.value("decisionKind","")=="AntiCheatRisk"&&!std::filesystem::exists(riskRoot/L"dxgi.dll"),"NH-ANTI-CHEAT: native plan cannot proceed for a candidate game without acknowledgment");nh::Json acknowledged;{std::ifstream file(risk.installer.request);acknowledged=nh::Json::parse(file);}check(acknowledged.value("proxyName","")=="dxgi.dll","NH-ANTI-CHEAT: unknown fixture explicitly selects its proxy before the independent risk gate");check(!acknowledged.contains("antiCheatAcknowledged")&&acknowledged["gameExecutable"]==nh::Utf8(riskExe.wstring())&&risk.showIssue,"NH-ANTI-CHEAT: warning remains pending without exporting approval in request JSON");
 risk.Plan("Install");wait();nh::Json fresh;{std::ifstream file(risk.installer.request);fresh=nh::Json::parse(file);}check(!fresh.contains("antiCheatAcknowledged")&&risk.operationIssue.value("decisionKind","")=="AntiCheatRisk"&&std::filesystem::last_write_time(riskExe)==exeTime&&!std::filesystem::exists(riskRoot/L"dxgi.dll"),"NH-ANTI-CHEAT: a new action requires fresh consent and review never mutates the game");
 ImGui::CreateContext();auto& io=ImGui::GetIO();io.IniFilename=io.LogFilename=nullptr;io.DisplaySize={1240,820};io.DeltaTime=1.f/60.f;io.BackendFlags|=ImGuiBackendFlags_RendererHasTextures|ImGuiBackendFlags_RendererHasVtxOffset;io.Fonts->AddFontFromMemoryCompressedBase85TTF(hack_compressed_compressed_data_base85,16.f);nh::ApplySharedTheme(false);
 // Exercise the real warning -> direct private-pipe writer path.
 // All targets here are copied Windows command fixtures, never installed games.
 auto renderRisk=[&]{ImGui::NewFrame();nh::RenderHub(risk,nullptr,1);ImGui::Render();};
 auto consumedRiskPlan=risk.plan;risk.AcknowledgeRisk();nh::Json executeRequest;{std::ifstream file(risk.installer.request);executeRequest=nh::Json::parse(file);}check(executeRequest.value("kind","")=="Execute"&&!executeRequest.contains("antiCheatAcknowledged")&&!risk.showReview,"NH-ANTI-CHEAT: explicit local acknowledgment executes without routine review or JSON approval");for(int i=0;i<3;i++)renderRisk();wait();
 check(std::filesystem::exists(riskRoot/L"dxgi.dll"),"NH-ANTI-CHEAT: rendered processing preserves local approval through the existing writer");
 risk.installer.StartInstaller({{"kind","Execute"},{"planId",consumedRiskPlan["planId"]},{"planFingerprint",consumedRiskPlan["planFingerprint"]}});wait();
 check(risk.lastResult.value("status","")=="FailedWithoutChanges","NH-ANTI-CHEAT: one-shot current transaction cannot be replayed after consumption");
 risk.Plan("Install");wait();auto previousRiskFingerprint=risk.plan["antiCheat"].value("fingerprint","");auto installedTime=std::filesystem::last_write_time(riskRoot/L"dxgi.dll");
 std::filesystem::copy_file(riskExe,riskRoot/L"EasyAntiCheat_EOS_Setup.exe",std::filesystem::copy_options::overwrite_existing);risk.AcknowledgeRisk();wait();
 check(risk.showIssue&&risk.operationIssue.value("decisionKind","")=="AntiCheatRisk"&&std::filesystem::last_write_time(riskRoot/L"dxgi.dll")==installedTime,"NH-ANTI-CHEAT: changed provider evidence returns to warning before Install writes");
 risk.AcknowledgeRisk();wait();
 check(risk.showIssue&&!risk.showReview&&risk.plan["antiCheat"].value("fingerprint","")!=previousRiskFingerprint,"NH-ANTI-CHEAT: changed evidence builds a fresh plan and warning instead of reapproving the stale plan");
 std::filesystem::remove(riskRoot/L"EasyAntiCheat_EOS_Setup.exe");risk.AcknowledgeRisk();wait();risk.AcknowledgeRisk();wait();
 check(risk.showIssue&&!risk.showReview&&risk.operationIssue["antiCheat"].contains("stale_findings")&&!risk.operationIssue["antiCheat"]["stale_findings"].empty(),"NH-ANTI-CHEAT: incomplete fresh-plan warning retains earlier positive provider findings");
 renderRisk();io.AddKeyEvent(ImGuiKey_Escape,true);renderRisk();io.AddKeyEvent(ImGuiKey_Escape,false);renderRisk();
 check(!risk.showIssue&&!risk.showReview&&std::filesystem::last_write_time(riskRoot/L"dxgi.dll")==installedTime,"NH-ANTI-CHEAT: Escape defaults to Back without game mutations");
 risk.Plan("Uninstall");check(risk.showUninstallConfirm&&!risk.showIssue&&!risk.installer.busy,"NH-ANTI-CHEAT: uninstall confirmation precedes installer work without detector approval");risk.ConfirmUninstall();wait();check(!risk.showReview&&!std::filesystem::exists(riskRoot/L"dxgi.dll"),"NH-ANTI-CHEAT: confirmed uninstall finishes without a second inventory review");
 nh::HubModel ui;ui.page=1;ui.reducedMotion=true;ui.games={game};ui.selected=0;ui.inspection={{"state",{{"status","installed-verified"}}},{"recoveryRequired",false}};
 std::string rendered;auto render=[&]{ImGui::NewFrame();ImGui::LogToBuffer();nh::RenderHub(ui,nullptr,1);rendered=GImGui->LogBuffer.c_str();ImGui::LogFinish();ImGui::Render();};io.DisplaySize.y=600;for(int i=0;i<4;i++)render();
 auto window=[&](const char* part){for(auto w:GImGui->Windows)if(w->Active&&strstr(w->Name,part))return w;return (ImGuiWindow*)nullptr;};auto details=window("GameDetails");ImGuiTabBar* tabs=nullptr;
 auto tabId=[](ImGuiTabBar& bar,const char* name){for(auto& tab:bar.Tabs)if(std::strcmp(ImGui::TabBarGetTabName(&bar,&tab),name)==0)return tab.ID;return ImGuiID(0);};
 for(auto& bar:GImGui->TabBars.Buf)if(tabId(bar,"Installation")&&tabId(bar,"INI Settings")&&tabId(bar,"Game Settings")&&tabId(bar,"Diagnostics"))tabs=&bar;
 auto headerWindow=window("SelectedGameHeader"),listWindow=window("LibraryList"),columnWindow=window("LibraryColumn");
 check(headerWindow&&details&&headerWindow->Pos.x>details->Pos.x+50&&listWindow&&columnWindow&&std::abs(listWindow->Pos.y+listWindow->Size.y-(columnWindow->Pos.y+columnWindow->Size.y))<25,"NH-FRONTDOOR: library list uses remaining height without a duplicate launch footer");
 check(details&&tabs&&details->ScrollMax.y>0&&!window("InstallationScroll"),"NH-GAME-TABS: installation overflows into one right-side scroll pane");
 if(listWindow){ImVec2 row{listWindow->Pos.x+listWindow->WindowPadding.x,listWindow->Pos.y+listWindow->WindowPadding.y};io.AddMousePosEvent(row.x+100,row.y+25);render();bool before=ui.games[0].favorite;io.AddMousePosEvent(row.x+14,row.y+25);io.AddMouseButtonEvent(0,true);render();io.AddMouseButtonEvent(0,false);render();check(ui.games[0].favorite!=before&&ui.selected==0,"NH-FAVORITES-UI: moving from row to star while clicking toggles favorite without selecting again");}
 if(details&&headerWindow&&tabs){
  const float headerY=headerWindow->Pos.y,detailsY=details->Pos.y;bool hovered=false;auto bounds=details->InnerRect;
  for(float y:{.15f,.5f,.85f}){for(float x:{.03f,.3f,.7f}){io.AddMousePosEvent(bounds.Min.x+bounds.GetWidth()*x,bounds.Min.y+bounds.GetHeight()*y);render();if(GImGui->HoveredWindow==details){hovered=true;break;}}if(hovered)break;}
  if(hovered){io.AddMouseWheelEvent(0,-6);render();for(int i=0;i<3;i++)render();}
  check(hovered&&details->Scroll.y>0&&headerWindow->Pos.y<headerY-1&&details->Pos.y==detailsY,"NH-GAME-TABS: real wheel input scrolls the cover and header with the entire right-side content");
  auto first=tabId(*tabs,"Installation");tabs->NextSelectedTabId=tabId(*tabs,"Game Settings");for(int i=0;i<3;i++)render();check(!window("SettingsScroll")&&rendered.find("Select a compatible game executable")!=std::string::npos&&details->Pos.y==detailsY,"NH-GAME-TABS: game settings render in the same outer scroll pane");
  tabs->NextSelectedTabId=tabId(*tabs,"INI Settings");for(int i=0;i<3;i++)render();check(rendered.find("Select a compatible game executable")!=std::string::npos&&details->Pos.y==detailsY,"NH-GAME-TABS: compatibility renders in the same outer scroll pane");
  tabs->NextSelectedTabId=tabId(*tabs,"Diagnostics");for(int i=0;i<3;i++)render();check(!window("DiagnosticsScroll")&&rendered.find("Quick log preview")!=std::string::npos&&details->Pos.y==detailsY,"NH-GAME-TABS: diagnostics render in the same outer scroll pane");
  tabs->NextSelectedTabId=first;for(int i=0;i<3;i++)render();check(!window("InstallationScroll")&&window("GameDetails")==details&&rendered.find("File Proxy Name")!=std::string::npos&&rendered.find("Unfamiliar files are handled individually")!=std::string::npos,"NH-GAME-TABS: returning to installation preserves the shared scroll owner and real proxy controls");
 }
 ui.installer.busy=ui.installer.readOnlyInstaller=true;ui.inspectionRefreshing=true;ui.installer.action="Inspect";for(int i=0;i<3;i++)render();auto shade=window("SelectedGameLoadingShade");details=window("GameDetails");check(shade&&details&&!window("Working")&&shade->Pos.x>=details->Pos.x&&shade->Pos.y>=details->Pos.y&&shade->Pos.x+shade->Size.x<=details->Pos.x+details->Size.x+1&&shade->Pos.y+shade->Size.y<=details->Pos.y+details->Size.y+1,"NH-PROFILE-UI: fresh inspection shows a loading shade confined to selected-game details");ui.installer.busy=false;ui.inspectionRefreshing=false;ui.games[0].title=std::string(1000,'W');io.DisplaySize={880,600};for(int i=0;i<4;i++)render();details=window("GameDetails");check(details&&details->InnerRect.GetHeight()>=70&&!window("InstallationScroll")&&!window("SelectedGameLoadingShade")&&rendered.find("File Proxy Name")!=std::string::npos&&rendered.find("Unfamiliar files are handled individually")!=std::string::npos,"NH-GAME-TABS: compact long title retains a usable shared viewport and installation controls after loading finishes");io.DisplaySize={1240,820};
 ui.operationIssue=issue.operationIssue;ui.showIssue=true;for(int i=0;i<3;i++)render();check(!GImGui->OpenPopupStack.empty()&&ImGui::GetDrawData()->TotalIdxCount>0,"NH-RECOVERY-UI: actionable conflict modal renders outside disabled game controls");
 ui.operationIssue={{"decisionKind","FileConflict"},{"fileConflicts",nh::Json::array({{{"path","dxgi.dll"},{"sha256",std::string(64,'a')}}})}};ui.fileReview.Begin(ui.operationIssue["fileConflicts"]);ui.showIssue=true;for(int i=0;i<3;i++)render();
 check(rendered.find("dxgi.dll appears to not have come from NeuRotic. How should we proceed?")!=std::string::npos&&rendered.find("Save and Replace")==std::string::npos&&rendered.find("Replace")!=std::string::npos&&rendered.find("Skip")!=std::string::npos&&rendered.find("Cancel")!=std::string::npos&&rendered.find("Check again")==std::string::npos,"NH-FILE-REVIEW: exact prompt and three decisions render without legacy recovery actions");
 ui.fileReview.Cancel();
 ui.operationIssue={{"decisionKind","AntiCheatRisk"},{"target",exe},{"antiCheat",{{"status","Unknown"},{"reason","List unavailable"},{"dataset",{{"reviewDate",nullptr}}}}}};for(int i=0;i<3;i++)render();check(ImGui::GetDrawData()->TotalIdxCount>0,"NH-ANTI-CHEAT-UI: unavailable dataset with null date renders a usable warning");ImGui::DestroyContext();
 return failed;
}catch(const std::exception& error){
 std::cout<<"FAIL NH-FIFTH-PASS: "<<error.what()<<'\n';if(ImGui::GetCurrentContext())ImGui::DestroyContext();return 1;
}
