#pragma once
#include "CapabilityContract.h"
namespace DlssNr::Capability {
enum class CapabilityId : uint8_t { FingerprintField, ModuleExport, VendorFeatureSupport, NgxRawRequirements, NgxEffectiveRequirements, ParameterSyntheticDefaults, ParameterStorage, ParameterDeclared, ParameterCreateAcceptance, ParameterEvaluateAcceptance, ParameterCausalEffect, ConfigRequestedEnabled, ConfigRequestedRoute, ConfigEffectiveEnabled, NativeOwnerState, NativeCounter, PresentOwnerState, PresentCounter, ProviderOwnerSupport, ProviderEnabled, HdrColorClass, HdrMetadata, LifecycleOpen, SignalOwnerReceipt, DiscoveryCandidate, AuxiliaryObserved, RouteOwnerDecision, ExecCreateReturn, ExecEvaluateReturn, ExecSubmit, ExecComplete, ExecOutput, ExecDeliver, ExecRetire, QualificationStability, QualificationImageQuality, QualificationPerformance, RouteOwnerHealth, Count };
struct Profile { SourceKind source; Basis basis; };
struct RegistryEntry { std::string_view id; AssertionKind kind; uint32_t producers,domains,qualifiers; std::string_view fields; ScalarType scalar; bool scalarRestricted, requiresNoMutation; std::array<Profile,4> profiles; uint8_t profileCount; };
inline constexpr std::array<RegistryEntry,38> Registry{{
{"nr.cap.fingerprint.field",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Identity)),(1u<<static_cast<unsigned>(Dimension::Process)),(1u<<static_cast<unsigned>(Qualifier::Field)),"",ScalarType::Bool,false,true,{{{SourceKind::FileObservation,Basis::T1},{SourceKind::PlatformObservation,Basis::T2},{SourceKind::OwnerObservation,Basis::T5},{SourceKind::RawApiBoundary,Basis::T5}}},4},
{"nr.cap.module.export",AssertionKind::Availability,(1u<<static_cast<unsigned>(ProducerId::Identity)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Module)),(1u<<static_cast<unsigned>(Qualifier::Field))|(1u<<static_cast<unsigned>(Qualifier::ModuleRole)),"",ScalarType::Bool,false,true,{{{SourceKind::FileObservation,Basis::T1}}},1},
{"nr.cap.vendor.feature_support",AssertionKind::Support,(1u<<static_cast<unsigned>(ProducerId::Ngx)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter))|(1u<<static_cast<unsigned>(Dimension::Driver))|(1u<<static_cast<unsigned>(Dimension::Provider)),(1u<<static_cast<unsigned>(Qualifier::FeatureNamespace))|(1u<<static_cast<unsigned>(Qualifier::FeatureId)),"",ScalarType::Bool,false,true,{{{SourceKind::VendorQuery,Basis::T3}}},1},
{"nr.cap.ngx.raw_requirements",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Ngx)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter))|(1u<<static_cast<unsigned>(Dimension::Provider)),(1u<<static_cast<unsigned>(Qualifier::Field))|(1u<<static_cast<unsigned>(Qualifier::FeatureNamespace))|(1u<<static_cast<unsigned>(Qualifier::FeatureId)),"return_code|FeatureSupported|MinHWArchitecture",ScalarType::U64,true,false,{{{SourceKind::RawApiBoundary,Basis::T5}}},1},
{"nr.cap.ngx.effective_requirements",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Ngx)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Configuration)),(1u<<static_cast<unsigned>(Qualifier::Field))|(1u<<static_cast<unsigned>(Qualifier::FeatureNamespace))|(1u<<static_cast<unsigned>(Qualifier::FeatureId)),"return_code|FeatureSupported|MinHWArchitecture",ScalarType::U64,true,false,{{{SourceKind::EffectivePolicy,Basis::T0}}},1},
{"nr.cap.parameter.synthetic_defaults",AssertionKind::Availability,(1u<<static_cast<unsigned>(ProducerId::Parameters)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::ParameterBlock)),0,"",ScalarType::Bool,false,false,{{{SourceKind::SyntheticDefault,Basis::T0}}},1},
{"nr.cap.parameter.storage",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Parameters)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::ParameterBlock)),(1u<<static_cast<unsigned>(Qualifier::ParameterName))|(1u<<static_cast<unsigned>(Qualifier::ParameterType))|(1u<<static_cast<unsigned>(Qualifier::ParameterPhase)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5},{SourceKind::RawApiBoundary,Basis::T5}}},2},
{"nr.cap.parameter.declared",AssertionKind::Availability,(1u<<static_cast<unsigned>(ProducerId::Parameters)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Provider)),(1u<<static_cast<unsigned>(Qualifier::ParameterName))|(1u<<static_cast<unsigned>(Qualifier::ParameterType))|(1u<<static_cast<unsigned>(Qualifier::ParameterPhase)),"",ScalarType::Bool,false,true,{{{SourceKind::FileObservation,Basis::T1},{SourceKind::VendorQuery,Basis::T3}}},2},
{"nr.cap.parameter.create_acceptance",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Native)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle)),(1u<<static_cast<unsigned>(Qualifier::ParameterName))|(1u<<static_cast<unsigned>(Qualifier::ParameterType))|(1u<<static_cast<unsigned>(Qualifier::ParameterPhase)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5},{SourceKind::RawApiBoundary,Basis::T5}}},2},
{"nr.cap.parameter.evaluate_acceptance",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Native)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),(1u<<static_cast<unsigned>(Qualifier::ParameterName))|(1u<<static_cast<unsigned>(Qualifier::ParameterType))|(1u<<static_cast<unsigned>(Qualifier::ParameterPhase)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5},{SourceKind::RawApiBoundary,Basis::T5}}},2},
{"nr.cap.parameter.causal_effect",AssertionKind::Qualification,(1u<<static_cast<unsigned>(ProducerId::Qualification)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter))|(1u<<static_cast<unsigned>(Dimension::Driver))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::GameSession)),(1u<<static_cast<unsigned>(Qualifier::ParameterName))|(1u<<static_cast<unsigned>(Qualifier::ParameterType))|(1u<<static_cast<unsigned>(Qualifier::ParameterPhase)),"",ScalarType::Bool,false,true,{{{SourceKind::QualificationReceipt,Basis::T6}}},1},
{"nr.cap.config.requested_enabled",AssertionKind::Enablement,(1u<<static_cast<unsigned>(ProducerId::Config)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Configuration)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.config.requested_route",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Config)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Configuration)),0,"",ScalarType::U64,true,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.config.effective_enabled",AssertionKind::Enablement,(1u<<static_cast<unsigned>(ProducerId::Orchestration)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Lifecycle)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.native.owner_state",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Native)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::Configuration)),(1u<<static_cast<unsigned>(Qualifier::Field)),"running|transitionPending|outputQuarantined|failed|modelLoaded|preSrDisplayReady|resetPending|nativeRayReconstructionActive",ScalarType::Bool,true,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.native.counter",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Native)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Lifecycle)),(1u<<static_cast<unsigned>(Qualifier::Field)),"frames|gameResets|featureBuilds|featureRebuilds|evaluateFailures|successfulEvaluations|completedPipelineEvaluations",ScalarType::U64,true,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.present.owner_state",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Present)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Swapchain))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::HdrDescriptor))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),(1u<<static_cast<unsigned>(Qualifier::Field)),"requested|active|failed|policyBlocked|historyResetPending",ScalarType::Bool,true,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.present.counter",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Present)),(1u<<static_cast<unsigned>(Dimension::Process)),(1u<<static_cast<unsigned>(Qualifier::Field))|(1u<<static_cast<unsigned>(Qualifier::ScopeCategory)),"modelEvaluations|compositeEvaluations|skippedFrames|modelSubmissions|compositeSubmissions|presentAttempts|consecutiveFallbacks|pendingSlots",ScalarType::U64,true,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.provider.owner_support",AssertionKind::Support,(1u<<static_cast<unsigned>(ProducerId::Provider)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Provider)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.provider.enabled",AssertionKind::Enablement,(1u<<static_cast<unsigned>(ProducerId::Provider)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Provider)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.hdr.color_class",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Hdr)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Swapchain))|(1u<<static_cast<unsigned>(Dimension::HdrDescriptor)),(1u<<static_cast<unsigned>(Qualifier::Field)),"colorClass",ScalarType::Text,true,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.hdr.metadata",AssertionKind::Scalar,(1u<<static_cast<unsigned>(ProducerId::Hdr)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Swapchain))|(1u<<static_cast<unsigned>(Dimension::HdrMetadata)),(1u<<static_cast<unsigned>(Qualifier::Field)),"metadataType|metadataSize|metadataHash|metadataResult|requestedMetadataType|requestedMetadataSize|requestedMetadataHash",ScalarType::U64,true,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.lifecycle.open",AssertionKind::Availability,(1u<<static_cast<unsigned>(ProducerId::Lifecycle)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Lifecycle)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.signal.owner_receipt",AssertionKind::OwnerReceipt,(1u<<static_cast<unsigned>(ProducerId::Semantic)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.discovery.candidate",AssertionKind::Availability,(1u<<static_cast<unsigned>(ProducerId::Discovery)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.auxiliary.observed",AssertionKind::Availability,(1u<<static_cast<unsigned>(ProducerId::Auxiliary)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.route.owner_decision",AssertionKind::OwnerReceipt,(1u<<static_cast<unsigned>(ProducerId::Orchestration)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle)),0,"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.exec.create_return",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Native)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle)),(1u<<static_cast<unsigned>(Qualifier::OperationId)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5},{SourceKind::RawApiBoundary,Basis::T5}}},2},
{"nr.cap.exec.evaluate_return",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Native)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),(1u<<static_cast<unsigned>(Qualifier::OperationId)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5},{SourceKind::RawApiBoundary,Basis::T5}}},2},
{"nr.cap.exec.submit",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Present))|(1u<<static_cast<unsigned>(ProducerId::Lifecycle)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Queue))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),(1u<<static_cast<unsigned>(Qualifier::OperationId)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.exec.complete",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Lifecycle)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Queue))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),(1u<<static_cast<unsigned>(Qualifier::OperationId)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.exec.output",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Native))|(1u<<static_cast<unsigned>(ProducerId::Present)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),(1u<<static_cast<unsigned>(Qualifier::OperationId)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.exec.deliver",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Present)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Queue))|(1u<<static_cast<unsigned>(Dimension::Swapchain))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Lifecycle))|(1u<<static_cast<unsigned>(Dimension::Frame))|(1u<<static_cast<unsigned>(Dimension::ResourceSet)),(1u<<static_cast<unsigned>(Qualifier::OperationId)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.exec.retire",AssertionKind::Result,(1u<<static_cast<unsigned>(ProducerId::Lifecycle)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Device))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Feature))|(1u<<static_cast<unsigned>(Dimension::Lifecycle)),(1u<<static_cast<unsigned>(Qualifier::OperationId)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
{"nr.cap.qualification.stability",AssertionKind::Qualification,(1u<<static_cast<unsigned>(ProducerId::Qualification)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::GameSession))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter))|(1u<<static_cast<unsigned>(Dimension::Driver))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Configuration)),(1u<<static_cast<unsigned>(Qualifier::Protocol))|(1u<<static_cast<unsigned>(Qualifier::GameBuild)),"",ScalarType::Bool,false,true,{{{SourceKind::QualificationReceipt,Basis::T6}}},1},
{"nr.cap.qualification.image_quality",AssertionKind::Qualification,(1u<<static_cast<unsigned>(ProducerId::Qualification)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::GameSession))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter))|(1u<<static_cast<unsigned>(Dimension::Driver))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Configuration)),(1u<<static_cast<unsigned>(Qualifier::Protocol))|(1u<<static_cast<unsigned>(Qualifier::GameBuild)),"",ScalarType::Bool,false,true,{{{SourceKind::QualificationReceipt,Basis::T6}}},1},
{"nr.cap.qualification.performance",AssertionKind::Qualification,(1u<<static_cast<unsigned>(ProducerId::Qualification)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::GameSession))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter))|(1u<<static_cast<unsigned>(Dimension::Driver))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Configuration)),(1u<<static_cast<unsigned>(Qualifier::Protocol))|(1u<<static_cast<unsigned>(Qualifier::GameBuild)),"",ScalarType::Bool,false,true,{{{SourceKind::QualificationReceipt,Basis::T6}}},1},
{"nr.cap.route.owner_health",AssertionKind::Health,(1u<<static_cast<unsigned>(ProducerId::Orchestration)),(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Route))|(1u<<static_cast<unsigned>(Dimension::Configuration))|(1u<<static_cast<unsigned>(Dimension::Lifecycle)),(1u<<static_cast<unsigned>(Qualifier::Field)),"",ScalarType::Bool,false,true,{{{SourceKind::OwnerObservation,Basis::T5}}},1},
}};
inline const RegistryEntry* Lookup(CapabilityId id) noexcept { auto i=static_cast<size_t>(id); return i<Registry.size()?&Registry[i]:nullptr; }
inline uint32_t RequiredDomains(const RegistryEntry& r,std::string_view field) noexcept {
 uint32_t m=r.domains; if(r.id=="nr.cap.fingerprint.field") {
 if(field.starts_with("/collector/")) m|=(1u<<static_cast<unsigned>(Dimension::Process));
 if(field.starts_with("/subject/")) m|=(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::GameSession));
 if(field.starts_with("/adapter/")) m|=(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter));
 if(field.starts_with("/driver/")) m|=(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Adapter))|(1u<<static_cast<unsigned>(Dimension::Driver));
 if(field.starts_with("/modules/")) m|=(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Provider))|(1u<<static_cast<unsigned>(Dimension::Module));
 if(field.starts_with("/feature_target/")) m|=(1u<<static_cast<unsigned>(Dimension::Process))|(1u<<static_cast<unsigned>(Dimension::Api))|(1u<<static_cast<unsigned>(Dimension::Provider));
 } return m; }
inline constexpr std::array<std::string_view,22> DimensionNames{"process","game_session","api","adapter","driver","device","queue","swapchain","provider","module","feature","route","view","pass","frame","configuration","lifecycle","hdr_descriptor","hdr_metadata","history","resource_set","parameter_block"};
inline constexpr std::array<std::string_view,14> QualifierNames{"field","feature_namespace","feature_id","module_role","parameter_id","parameter_name","parameter_type","parameter_phase","operation_id","view_id","pass_id","protocol","game_build","scope_category"};
inline constexpr std::array<std::string_view,12> SourceKindNames{"owner_observation","raw_api_boundary","vendor_query","effective_policy","file_observation","platform_observation","synthetic_default","inference","historical_import","user_report","fixture","qualification_receipt"};
inline constexpr std::array<std::string_view,15> ProducerIdNames{"identity","ngx","config","parameters","native","present","lifecycle","semantic","discovery","auxiliary","provider","hdr","orchestration","qualification","ui"};
}
