"""Offline maintenance for directly authored UI translations. No network access.

materialize: import authored.tsv against its frozen en.json inventory.
build/verify: validate editable keyed JSON and emit/check the bundled C++ catalog.
"""
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEST = ROOT / 'OptiScaler/menu/locales'
LANGUAGES = ['es', 'fr', 'de', 'pt']
FORMAT = re.compile(r'%(?:[-+#0]*\d*(?:\.\d+)?(?:hh|ll|[hljztL]|I64)?[diuoxXfFeEgGaAcsp]|%)|\{(?::[^{}]*)?\}')

def extra_rows():
    return [line.split('\t') for line in (DEST / 'extra.tsv').read_text(encoding='utf-8').splitlines()
            if line and not line.startswith('#')]

def inventory():
    return json.loads((DEST / 'en.json').read_text(encoding='utf-8')) + [row[0] for row in extra_rows()]

def materialize():
    source = json.loads((DEST / 'en.json').read_text(encoding='utf-8'))
    (DEST / 'en.json').write_text(json.dumps(source, ensure_ascii=False, indent=2) + '\n',
                                  encoding='utf-8', newline='\n')
    rows = {}
    for line in (DEST / 'authored.tsv').read_text(encoding='utf-8').splitlines():
        if not line or line.startswith('#'):
            continue
        fields = line.split('\t')
        if len(fields) != len(LANGUAGES) + 1:
            raise ValueError(f'Expected five fields: {line[:100]}')
        index = int(fields[0])
        if index in rows or not 0 <= index < len(source):
            raise ValueError(f'Duplicate or out-of-range row {index}')
        rows[index] = fields[1:]
    if set(rows) != set(range(len(source))):
        raise ValueError(f'Missing rows: {sorted(set(range(len(source))) - rows.keys())}')
    def resolve(index, language, seen):
        if index in seen:
            raise ValueError(f'Cyclic alias at {index}')
        value = rows[index][language]
        if value == '=':
            return source[index]
        if value.startswith('@') and value[1:].isdigit():
            return resolve(int(value[1:]), language, seen | {index})
        return value
    for i, language in enumerate(LANGUAGES):
        data = {key: resolve(index, i, set()) for index, key in enumerate(source)}
        for row in extra_rows():
            if len(row) != 5:
                raise ValueError(f'Expected five extra fields: {row}')
            data[row[0]] = row[i + 1]
        (DEST / (language + '.json')).write_text(
            json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + '\n', encoding='utf-8', newline='\n')
    verify()

def cpp(value):
    return '"' + ''.join(chr(b) if 32 <= b < 127 and b not in (34, 92)
                         else f'\\{b:03o}' for b in value.encode('utf-8')) + '"'

def verify():
    source = inventory()
    if len(source) != len(set(source)):
        raise ValueError('Duplicate English keys')
    errors = []
    for language in LANGUAGES:
        data = json.loads((DEST / (language + '.json')).read_text(encoding='utf-8'))
        if set(source) != data.keys():
            errors.append(f'{language}: keys differ from English inventory')
        for index, key in enumerate(source):
            value = data.get(key, '')
            if not value or 'ZXQ' in value.upper():
                errors.append(f'{language} row {index}: invalid translation')
            if FORMAT.findall(key) != FORMAT.findall(value):
                errors.append(f'{language} row {index}: format mismatch {FORMAT.findall(key)} != {FORMAT.findall(value)}')
        print(f'{language}: {len(data)} entries')
    if errors:
        raise ValueError('\n'.join(errors))
    print(f'PASS: {len(source)} entries in each of four languages; format arguments preserved')

def build():
    verify()
    catalogs = [json.loads((DEST / (lang + '.json')).read_text(encoding='utf-8')) for lang in LANGUAGES]
    rows = ['// Generated by tools/localization/catalog.py build. Edit locale JSON, not this file.',
            'static const CatalogEntry Catalog[] = {']
    for key in inventory():
        rows.append('    {' + cpp(key) + ', {' + ', '.join(cpp(c[key]) for c in catalogs) + '}},')
    rows.append('};\n')
    (DEST / 'catalog.inc').write_text('\n'.join(rows), encoding='ascii', newline='\n')
    print('Bundled catalog SHA256:', hashlib.sha256((DEST / 'catalog.inc').read_bytes()).hexdigest())

if __name__ == '__main__':
    {'materialize': materialize, 'build': build, 'verify': verify}[sys.argv[1]]()
