#include "FrameProbe.h"
#include "FrameProbeShader.h"
#include <d3dcompiler.h>
#include <cstring>
namespace nrw {
namespace {
void ProbeCheck(HRESULT hr,const char* reason){if(FAILED(hr))throw std::runtime_error(reason);}
std::array<uint32_t,8> ProbeConstants(const ProbeIdentity& id,unsigned stage){return {id.frame.width|(stage<<16),id.frame.height,uint32_t(id.requestId),uint32_t(id.requestId>>32),uint32_t(id.frame.session),uint32_t(id.frame.session>>32),uint32_t(id.frame.sequence),uint32_t(id.frame.sequence>>32)};}
bool ProbeTexture(ID3D11Texture2D* texture,const ProbeIdentity& id,DXGI_FORMAT format){if(!texture)return false;D3D11_TEXTURE2D_DESC d{};texture->GetDesc(&d);return d.Width==id.frame.width&&d.Height==id.frame.height&&d.Format==format&&d.SampleDesc.Count==1&&d.MipLevels==1&&d.ArraySize==1;}
void ProbeBarrier(ID3D12GraphicsCommandList* list,ID3D12Resource* resource,D3D12_RESOURCE_STATES from,D3D12_RESOURCE_STATES to){if(from==to)return;D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={resource,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,from,to};list->ResourceBarrier(1,&b);}
}
struct FrameProbe::Impl {
 ProbeAdmission admission;bool attempted=false,allocated=false,nrRecorded=false,pubRecorded=false,comparisonRecorded=false,readbackCopied=false;
 ComPtr<ID3D12Device> d12;ComPtr<ID3D11Device> d11;ComPtr<ID3D11DeviceContext> context;
 ComPtr<ID3D12Resource> aggregate12,readback12;ComPtr<ID3D12DescriptorHeap> heap;ComPtr<ID3D12RootSignature> root;ComPtr<ID3D12PipelineState> pipeline;
 ComPtr<ID3D11Buffer> aggregate11,readback11,constants;ComPtr<ID3D11Texture2D> atlas;ComPtr<ID3D11ShaderResourceView> atlasView,publishedView,resolvedView;ComPtr<ID3D11UnorderedAccessView> aggregateView;ComPtr<ID3D11ComputeShader> shader;
 ComPtr<ID3DBlob> bytecode;std::array<ComPtr<ID3D12Resource>,4> input12;ComPtr<ID3D11Texture2D> published,backbuffer;
 ComPtr<ID3D12Fence> nrFence;ComPtr<ID3D11Fence> publicationFence,comparisonFence;uint64_t nrValue=0,pubValue=0,comparisonValue=0;
 ProbeJson summaries=nullptr;int alphaMode=-1;bool overlay=false;
 std::optional<std::array<uint32_t,24>> effectiveConstants;
 unsigned dispatches=0,sampleCopies=0,aggregateCopies=0;
 bool Allocate(ID3D12Device* device12,ID3D11Device* device11,ID3D11DeviceContext* ctx){
  if(allocated)return d12.Get()==device12&&d11.Get()==device11&&context.Get()==ctx;
  if(attempted)return false;attempted=true;d12=device12;d11=device11;context=ctx;
  ComPtr<ID3DBlob> errors;ProbeCheck(D3DCompile(FrameProbeShader,sizeof(FrameProbeShader)-1,"FrameProbe",nullptr,nullptr,"main","cs_5_0",D3DCOMPILE_ENABLE_STRICTNESS|D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&bytecode,&errors),"Compile fixed diagnostic shader");
  D3D12_DESCRIPTOR_RANGE ranges[2]{{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,4}};D3D12_ROOT_PARAMETER parameters[2]{};parameters[0].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;parameters[0].Constants={0,0,8};parameters[1].ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;parameters[1].DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=2;rd.pParameters=parameters;ComPtr<ID3DBlob> signature;
  ProbeCheck(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&signature,&errors),"Serialize fixed diagnostic root");ProbeCheck(d12->CreateRootSignature(0,signature->GetBufferPointer(),signature->GetBufferSize(),IID_PPV_ARGS(&root)),"Create fixed diagnostic root");D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root.Get();pd.CS={bytecode->GetBufferPointer(),bytecode->GetBufferSize()};ProbeCheck(d12->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pipeline)),"Create diagnostic pipeline");
  D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;hd.NumDescriptors=5;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;ProbeCheck(d12->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)),"Create five diagnostic descriptors");
  D3D12_RESOURCE_DESC buffer{};buffer.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;buffer.Width=256;buffer.Height=buffer.DepthOrArraySize=buffer.MipLevels=buffer.SampleDesc.Count=1;buffer.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;buffer.Flags=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;ProbeCheck(d12->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&buffer,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&aggregate12)),"Create 256-byte D12 aggregates");hp.Type=D3D12_HEAP_TYPE_READBACK;buffer.Flags=D3D12_RESOURCE_FLAG_NONE;ProbeCheck(d12->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&buffer,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&readback12)),"Create 256-byte D12 readback");
  D3D11_BUFFER_DESC bd{};bd.ByteWidth=256;bd.Usage=D3D11_USAGE_DEFAULT;bd.BindFlags=D3D11_BIND_UNORDERED_ACCESS;bd.MiscFlags=D3D11_RESOURCE_MISC_BUFFER_STRUCTURED;bd.StructureByteStride=128;ProbeCheck(d11->CreateBuffer(&bd,nullptr,&aggregate11),"Create 256-byte D11 aggregates");D3D11_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D11_UAV_DIMENSION_BUFFER;uv.Buffer.NumElements=2;ProbeCheck(d11->CreateUnorderedAccessView(aggregate11.Get(),&uv,&aggregateView),"Create diagnostic aggregate UAV");bd.Usage=D3D11_USAGE_STAGING;bd.BindFlags=bd.MiscFlags=bd.StructureByteStride=0;bd.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ProbeCheck(d11->CreateBuffer(&bd,nullptr,&readback11),"Create 256-byte D11 readback");bd={};bd.ByteWidth=32;bd.Usage=D3D11_USAGE_DEFAULT;bd.BindFlags=D3D11_BIND_CONSTANT_BUFFER;ProbeCheck(d11->CreateBuffer(&bd,nullptr,&constants),"Create 32-byte diagnostic constants");
  D3D11_TEXTURE2D_DESC td{};td.Width=td.Height=16;td.ArraySize=td.MipLevels=td.SampleDesc.Count=1;td.Format=DXGI_FORMAT_B8G8R8A8_UNORM;td.Usage=D3D11_USAGE_DEFAULT;td.BindFlags=D3D11_BIND_SHADER_RESOURCE;ProbeCheck(d11->CreateTexture2D(&td,nullptr,&atlas),"Create fixed 16x16 diagnostic atlas");ProbeCheck(d11->CreateShaderResourceView(atlas.Get(),nullptr,&atlasView),"Create diagnostic atlas view");ProbeCheck(d11->CreateComputeShader(bytecode->GetBufferPointer(),bytecode->GetBufferSize(),nullptr,&shader),"Create shared diagnostic compute shader");allocated=true;return true;
 }
 void Dispatch11(unsigned tag,ID3D11ShaderResourceView* a,ID3D11ShaderResourceView* b){
  context->ClearState();const auto values=ProbeConstants(admission.Identity(),tag);context->UpdateSubresource(constants.Get(),0,nullptr,values.data(),0,0);auto* cb=constants.Get();auto* uav=aggregateView.Get();ID3D11ShaderResourceView* views[]{a,b,nullptr,nullptr};context->CSSetConstantBuffers(0,1,&cb);context->CSSetShaderResources(0,4,views);context->CSSetUnorderedAccessViews(0,1,&uav,nullptr);context->CSSetShader(shader.Get(),nullptr,0);context->Dispatch(1,1,1);++dispatches;context->ClearState();
 }
 void Observe(){
  if(nrFence&&admission.Observe(ProbeStage::Nr,nrFence->GetCompletedValue()))input12={};
  if(publicationFence&&admission.Observe(ProbeStage::Publication,publicationFence->GetCompletedValue())){resolvedView.Reset();if(!admission.Pending()&&!comparisonRecorded){publishedView.Reset();published.Reset();}}
  if(comparisonFence&&admission.Observe(ProbeStage::Comparison,comparisonFence->GetCompletedValue())){backbuffer.Reset();publishedView.Reset();published.Reset();}
 }
};
FrameProbe::FrameProbe():impl(std::make_unique<Impl>()){}
FrameProbe::~FrameProbe(){if(!impl->admission.Retired())(void)impl.release();} // fixed owner retained to process exit when GPU last use is unproved
bool FrameProbe::Request(uint64_t id){auto& p=*impl;p.Observe();if(!p.admission.Request(id))return false;p.nrRecorded=p.pubRecorded=p.comparisonRecorded=p.readbackCopied=false;p.nrFence.Reset();p.publicationFence.Reset();p.comparisonFence.Reset();p.nrValue=p.pubValue=p.comparisonValue=0;p.input12={};p.published.Reset();p.backbuffer.Reset();p.publishedView.Reset();p.resolvedView.Reset();p.summaries=nullptr;p.effectiveConstants.reset();p.dispatches=p.sampleCopies=p.aggregateCopies=0;p.alphaMode=-1;return true;}
bool FrameProbe::Bind(const ProbeIdentity& id){return impl->admission.Bind(id);}
bool FrameProbe::Pending()const{return impl->admission.Pending();}
bool FrameProbe::Busy()const{return Pending()||!impl->admission.Retired();}
bool FrameProbe::Quarantined()const{return impl->admission.Quarantined();}
uint64_t FrameProbe::RequestId()const{return impl->admission.RequestId();}
const ProbeIdentity& FrameProbe::Identity()const{return impl->admission.Identity();}
void FrameProbe::Invalidate(const char* reason){impl->admission.Invalidate(reason);impl->summaries=nullptr;}
void FrameProbe::Refuse(const char* reason){impl->admission.Unsupported(reason);impl->summaries=nullptr;}
void FrameProbe::Unknown(const char* reason){impl->admission.Unknown(reason);impl->summaries=nullptr;}
bool FrameProbe::CaptureConstants(const std::array<uint32_t,24>& c){
 auto& p=*impl;if(!Pending()||p.nrRecorded)return false;const auto& id=Identity();const auto f=[&](unsigned i){return std::bit_cast<float>(c[i]);};
 if(c[0]!=1||f(1)!=1||c[2]!=id.frame.width||c[3]!=id.frame.height||f(4)!=id.transferStrength||f(5)!=id.colourStrength||c[6]!=0||f(7)!=2||c[8]!=1||f(9)!=1||f(10)!=1||c[13]!=0||f(14)!=0||f(15)!=1||c[16]!=0||c[17]!=1||f(18)!=1||c[19]!=0||c[20]!=1||c[21]!=0||f(22)!=1||c[23]!=0){Refuse("Effective NR resolve constants are outside the diagnostic contract");return false;}
 if(p.effectiveConstants&&*p.effectiveConstants!=c){Invalidate("Effective NR constants changed after admission");return false;}p.effectiveConstants=c;return true;
}
bool FrameProbe::RecordNr(ID3D12Device* d12,ID3D11Device* d11,ID3D11DeviceContext* context,ID3D12GraphicsCommandList* list,ID3D12Resource* model,ID3D12Resource* proxy,ID3D12Resource* resolved,ID3D12Resource* original){
 auto& p=*impl;if(!Pending()||p.nrRecorded||!list||!d12||!d11||!context)return false;const auto& id=Identity();std::array<ID3D12Resource*,4> resources{model,proxy,resolved,original};const DXGI_FORMAT formats[]{DXGI_FORMAT_R16G16B16A16_FLOAT,DXGI_FORMAT_R16G16B16A16_FLOAT,DXGI_FORMAT_R8G8B8A8_UNORM,DXGI_FORMAT_B8G8R8A8_UNORM};
 for(unsigned i=0;i<4;++i){for(unsigned j=0;j<i;++j)if(resources[i]&&resources[i]==resources[j]){Refuse("Diagnostic boundary resources alias");return false;}if(!resources[i]){Refuse("Diagnostic input resource is unavailable");return false;}const auto desc=resources[i]->GetDesc();ComPtr<ID3D12Device> device;if(FAILED(resources[i]->GetDevice(IID_PPV_ARGS(&device)))){p.admission.Fail("Diagnostic input device is unavailable");return false;}if(desc.Dimension!=D3D12_RESOURCE_DIMENSION_TEXTURE2D||desc.Width!=id.frame.width||desc.Height!=id.frame.height||desc.Format!=formats[i]||desc.SampleDesc.Count!=1||desc.MipLevels!=1||desc.DepthOrArraySize!=1||device.Get()!=d12){Refuse("Diagnostic input format, extent or device differs");return false;}}
 try{if(!p.Allocate(d12,d11,context)){p.admission.Fail("Fixed diagnostic allocation unavailable for this device");return false;}}catch(const std::exception& error){p.admission.Fail(error.what());return false;}
 auto cpu=p.heap->GetCPUDescriptorHandleForHeapStart();const auto step=d12->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
 for(unsigned i=0;i<4;++i){p.input12[i]=resources[i];D3D12_SHADER_RESOURCE_VIEW_DESC view{};view.Format=formats[i];view.ViewDimension=D3D12_SRV_DIMENSION_TEXTURE2D;view.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;view.Texture2D.MipLevels=1;d12->CreateShaderResourceView(resources[i],&view,cpu);cpu.ptr+=step;}
 D3D12_UNORDERED_ACCESS_VIEW_DESC uav{};uav.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uav.Buffer.NumElements=2;uav.Buffer.StructureByteStride=128;d12->CreateUnorderedAccessView(p.aggregate12.Get(),nullptr,&uav,cpu);
 p.admission.Record(ProbeStage::Nr);p.nrRecorded=true;
 // Actual retained Dispatch(2) leaves model/proxy/source NON_PIXEL and resolve UAV.
 ProbeBarrier(list,resolved,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);ID3D12DescriptorHeap* heaps[]{p.heap.Get()};list->SetDescriptorHeaps(1,heaps);list->SetComputeRootSignature(p.root.Get());list->SetPipelineState(p.pipeline.Get());const auto values=ProbeConstants(id,0);list->SetComputeRoot32BitConstants(0,8,values.data(),0);list->SetComputeRootDescriptorTable(1,p.heap->GetGPUDescriptorHandleForHeapStart());list->Dispatch(1,1,1);++p.dispatches;D3D12_RESOURCE_BARRIER barrier{};barrier.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;barrier.UAV.pResource=p.aggregate12.Get();list->ResourceBarrier(1,&barrier);ProbeBarrier(list,p.aggregate12.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);list->CopyBufferRegion(p.readback12.Get(),0,p.aggregate12.Get(),0,256);++p.aggregateCopies;ProbeBarrier(list,p.aggregate12.Get(),D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);ProbeBarrier(list,resolved,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);return true;
}
void FrameProbe::CompleteNr(ID3D12Fence* fence,uint64_t value){auto& p=*impl;if(!p.nrRecorded)return;if(!fence||!value){Unknown("NR diagnostic completion signal is unavailable");return;}if(p.nrFence&&(p.nrFence.Get()!=fence||p.nrValue!=value)){Unknown("NR diagnostic fence identity changed");return;}p.nrFence=fence;p.nrValue=value;p.admission.Require(ProbeStage::Nr,value);p.Observe();}
bool FrameProbe::RecordPublication(ID3D11DeviceContext* context,ID3D11Texture2D* published,ID3D11ShaderResourceView* resolved){
 auto& p=*impl;if(!Pending()||!p.nrRecorded||p.pubRecorded)return false;if(context!=p.context.Get()||!ProbeTexture(published,Identity(),DXGI_FORMAT_B8G8R8A8_UNORM)||!resolved){Invalidate("Publication input no longer matches the admitted frame");return false;}
 ComPtr<ID3D11Device> device;published->GetDevice(&device);ComPtr<ID3D11Resource> resolvedResource;resolved->GetResource(&resolvedResource);ComPtr<ID3D11Texture2D> resolvedTexture;
 if(device.Get()!=p.d11.Get()||FAILED(resolvedResource.As(&resolvedTexture))||!ProbeTexture(resolvedTexture.Get(),Identity(),DXGI_FORMAT_R8G8B8A8_UNORM)){Invalidate("Publication device or resolve resource differs");return false;}
 const HRESULT hr=p.d11->CreateShaderResourceView(published,nullptr,&p.publishedView);if(FAILED(hr)){p.admission.Fail("Diagnostic publication view allocation failed");return false;}p.published=published;p.resolvedView=resolved;p.admission.Record(ProbeStage::Publication);p.pubRecorded=true;context->ClearState();const UINT zeros[4]{};context->ClearUnorderedAccessViewUint(p.aggregateView.Get(),zeros);p.Dispatch11(1,p.publishedView.Get(),resolved);return true;
}
void FrameProbe::CompletePublication(ID3D11Fence* fence,uint64_t value){auto& p=*impl;if(!p.pubRecorded)return;if(!fence||!value){Unknown("Publication diagnostic completion signal is unavailable");return;}if(p.publicationFence&&(p.publicationFence.Get()!=fence||p.pubValue!=value)){Unknown("Publication diagnostic fence identity changed");return;}p.publicationFence=fence;p.pubValue=value;p.admission.Require(ProbeStage::Publication,value);p.Observe();}
bool FrameProbe::RecordComparison(ID3D11DeviceContext* context,ID3D11Texture2D* backbuffer,ID3D11Texture2D* published,uint64_t epoch,int alphaMode,bool overlay){
 auto& p=*impl;if(!Pending()||!p.pubRecorded||p.comparisonRecorded)return false;if(context!=p.context.Get()||published!=p.published.Get()||epoch!=Identity().outputEpoch||!ProbeTexture(backbuffer,Identity(),DXGI_FORMAT_B8G8R8A8_UNORM)){Invalidate("Comparison output epoch, extent or frame differs");return false;}ComPtr<ID3D11Device> device;backbuffer->GetDevice(&device);if(device.Get()!=p.d11.Get()){Invalidate("Comparison device differs");return false;}
 p.backbuffer=backbuffer;p.alphaMode=alphaMode;p.overlay=overlay;p.admission.Record(ProbeStage::Comparison);p.comparisonRecorded=true;context->ClearState();const auto& id=Identity();
 for(UINT j=0;j<16;++j){const UINT y=ProbeGridAxis(id.frame.height,j);if(j&&y==ProbeGridAxis(id.frame.height,j-1))continue;for(UINT i=0;i<16;++i){const UINT x=ProbeGridAxis(id.frame.width,i);if(i&&x==ProbeGridAxis(id.frame.width,i-1))continue;D3D11_BOX box{x,y,0,x+1,y+1,1};context->CopySubresourceRegion(p.atlas.Get(),0,i,j,0,backbuffer,0,&box);++p.sampleCopies;}}
 p.Dispatch11(2,p.atlasView.Get(),p.publishedView.Get());context->CopyResource(p.readback11.Get(),p.aggregate11.Get());++p.aggregateCopies;p.readbackCopied=true;return true;
}
void FrameProbe::RequireComparison(ID3D11Fence* fence,uint64_t value){auto& p=*impl;if(!p.comparisonRecorded)return;if(!fence||!value){Unknown("Comparison diagnostic completion signal is unavailable");return;}if(p.comparisonFence&&(p.comparisonFence.Get()!=fence||p.comparisonValue!=value)){Unknown("Comparison diagnostic fence identity changed");return;}p.comparisonFence=fence;p.comparisonValue=value;p.admission.Require(ProbeStage::Comparison,value);}
void FrameProbe::ObserveComparison(uint64_t completed){auto& p=*impl;if(!p.comparisonRecorded||!p.comparisonFence)return;if(completed==UINT64_MAX){Unknown("Comparison device loss leaves last use unproved");return;}p.Observe();} // A caller's number cannot replace observation of the bound fence object.
void FrameProbe::Poll(){
 auto& p=*impl;p.Observe();if(!Pending()||!p.comparisonRecorded||!p.readbackCopied||!p.admission.Retired())return;
 std::array<ProbeRecord,4> records{};void* data=nullptr;D3D12_RANGE range{0,256};const HRESULT nrMap=p.readback12->Map(0,&range,&data);if(FAILED(nrMap)){p.admission.Fail("Completed NR aggregate readback failed");return;}std::memcpy(records.data(),data,256);D3D12_RANGE noWrite{};p.readback12->Unmap(0,&noWrite);
 D3D11_MAPPED_SUBRESOURCE mapped{};const HRESULT map=p.context->Map(p.readback11.Get(),0,D3D11_MAP_READ,D3D11_MAP_FLAG_DO_NOT_WAIT,&mapped);if(map==DXGI_ERROR_WAS_STILL_DRAWING)return;if(FAILED(map)){p.admission.Fail("Completed publication/comparison readback failed");return;}std::memcpy(records.data()+2,mapped.pData,256);p.context->Unmap(p.readback11.Get(),0);
 ProbeJson results=ProbeJson::array();for(unsigned i=0;i<4;++i){auto decoded=DecodeProbeRecord(records[i],Identity(),i);if(!decoded){p.admission.Fail("Aggregate identity, finite metrics or denominator validation failed");return;}results.push_back(std::move(*decoded));}if(p.admission.Complete())p.summaries=std::move(results);
}
ProbeJson FrameProbe::Status()const{
 const auto& p=*impl;auto status=p.admission.Status();if(status["state"]!="complete")return status;status["summaries"]=p.summaries;const auto& id=Identity();status["identity"]={{"session",id.frame.session},{"sequence",id.frame.sequence},{"targetGeneration",id.targetGeneration},{"streamEpoch",id.frame.streamEpoch},{"geometryEpoch",id.frame.geometryEpoch},{"outputEpoch",id.outputEpoch},{"requestedRevision",id.requestedRevision},{"appliedRevision",id.appliedRevision},{"processingRevision",id.processingRevision},{"comparisonRevision",id.comparisonRevision},{"extent",{id.frame.width,id.frame.height}}};const auto adapter=p.d12->GetAdapterLuid();status["adapterLuid"]={{"lowPart",adapter.LowPart},{"highPart",adapter.HighPart}};status["effectiveProcessing"]={{"transferStrength",id.transferStrength},{"colourStrength",id.colourStrength},{"modelStyle",id.modelStyle},{"comparisonDirection",id.comparisonDirection},{"resolveConstantsDwords",p.effectiveConstants?ProbeJson(*p.effectiveConstants):ProbeJson(nullptr)}};status["sampling"]={{"grid",{16,16}},{"axisCoordinateRule","floor((2*i+1)*extent/32), i=0..15; clamp to extent-1; deduplicate each axis"},{"maximumUniqueSamples",256},{"coverage","fixed samples only; not whole-frame equality"}};status["formats"]={{"modelProxy","RGBA16F"},{"resolve","RGBA8 UNORM"},{"originalPublicationComparison","BGRA8 UNORM"}};status["output"]={{"alphaMode",p.alphaMode<0?ProbeJson(nullptr):ProbeJson(p.alphaMode)},{"mode",p.overlay?"overlay":"preview"},{"physicalDisplayQualified",false}};status["budget"]={{"resources",6},{"scratchConstantBytes",1568},{"aggregateReadbackBytes",512},{"maximumDispatches",3},{"maximumSampleCopies",256},{"aggregateCopies",2}};D3D11_BUFFER_DESC aggregateDesc{},readbackDesc{},constantDesc{};D3D11_TEXTURE2D_DESC atlasDesc{};p.aggregate11->GetDesc(&aggregateDesc);p.readback11->GetDesc(&readbackDesc);p.constants->GetDesc(&constantDesc);p.atlas->GetDesc(&atlasDesc);const auto a12=p.aggregate12->GetDesc(),r12=p.readback12->GetDesc();const auto ai=p.d12->GetResourceAllocationInfo(0,1,&a12),ri=p.d12->GetResourceAllocationInfo(0,1,&r12);
 status["budget"]["observed"]={{"resources",unsigned(bool(p.aggregate12))+unsigned(bool(p.readback12))+unsigned(bool(p.aggregate11))+unsigned(bool(p.readback11))+unsigned(bool(p.constants))+unsigned(bool(p.atlas))},{"scratchConstantBytes",a12.Width+aggregateDesc.ByteWidth+constantDesc.ByteWidth+uint64_t(atlasDesc.Width)*atlasDesc.Height*4},{"aggregateReadbackBytes",r12.Width+readbackDesc.ByteWidth},{"dispatches",p.dispatches},{"sampleCopies",p.sampleCopies},{"aggregateCopies",p.aggregateCopies},{"atlasExtent",{atlasDesc.Width,atlasDesc.Height}},{"structuredRecordBytes",aggregateDesc.StructureByteStride},{"d12Allocation",{{"aggregateSize",ai.SizeInBytes},{"aggregateAlignment",ai.Alignment},{"readbackSize",ri.SizeInBytes},{"readbackAlignment",ri.Alignment}}},{"d11PhysicalAllocationBytes",nullptr}};return status;
}
}
