#include <menu/Localization.h>
#pragma once
#include "../../../OptiScaler/nr/semantic/object_rules/ObjectRuleEditor.h"
#include <commdlg.h>
#include <fstream>
namespace nh {
inline std::filesystem::path PickRuleFile(bool save){wchar_t path[32768]{};OPENFILENAMEW dialog{sizeof(dialog)};dialog.hwndOwner=GetActiveWindow();dialog.lpstrFile=path;dialog.nMaxFile=32768;dialog.lpstrFilter=L"Object Rules JSON (*.json)\0*.json\0\0";dialog.lpstrDefExt=L"json";dialog.Flags=OFN_PATHMUSTEXIST|OFN_NOCHANGEDIR|OFN_DONTADDTORECENT|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);return (save?GetSaveFileNameW(&dialog):GetOpenFileNameW(&dialog))?std::filesystem::path(path):std::filesystem::path();}
inline void DrawObjectRuleHost(SettingsField& field,const std::vector<SettingsField>& settings){
    using namespace Neurotic::Semantic::Rules;
    ImGui::TextWrapped(Neurotic::UiLiteral("desktop.objectrulehost.object_rules_is_an_early_foundation_for_broader__cbef72ba", "Object Rules is an early foundation for broader capabilities. Additional updates are planned."));
    ImGui::TextWrapped(Neurotic::UiLiteral("desktop.objectrulehost.save_detection_and_overlay_rules_for_the_next_la_242ab62e", "Save detection and overlay rules for the next launch. Per-object NR recipes and mask-based effects are not active; live detection must be enabled in game."));
    ImGui::TextWrapped(Neurotic::UiLiteral("desktop.objectrulehost.apply_each_rule_edit_to_this_profile_then_use_re_17e3f110", "Apply each rule edit to this profile, then use Review settings changes to save the profile to the game."));
    try{
        if(!field.ruleStore){field.ruleStore=std::make_shared<Store>();field.ruleEditor=std::make_shared<Editor>();if(field.profileDraft!=Neurotic::UiLiteral("desktop.gamesettingsview.auto_d1f397f2", "auto")&&!field.profileDraft.empty()){auto ack=field.ruleStore->Commit(0,DecodeIni(field.profileDraft));Require(ack.accepted,ack.reason.c_str());}else field.ruleStore->Commit(0,DefaultProfile());}
        auto revision=field.ruleStore->Read()->revision;Host host;host.desktop=true;host.runtime=Neurotic::UiLiteral("desktop.objectrulehost.offline_profile_editor_live_detection_is_control_f00305e0", "Offline profile editor. Live detection is controlled in-game; save with the game closed.");
        host.importFile=[](){auto path=PickRuleFile(false);if(path.empty())return std::string();Require(std::filesystem::file_size(path)<=MaxBytes,Neurotic::UiLiteral("desktop.objectrulehost.profile_exceeds_2_mib_b1dee5ce", "Profile exceeds 2 MiB"));std::ifstream f(path,std::ios::binary);Require(bool(f),Neurotic::UiLiteral("desktop.objectrulehost.cannot_read_profile_dab49fca", "Cannot read profile"));std::string data(MaxBytes+1,'\0');f.read(data.data(),static_cast<std::streamsize>(data.size()));data.resize(static_cast<size_t>(f.gcount()));Require(data.size()<=MaxBytes,Neurotic::UiLiteral("desktop.objectrulehost.profile_exceeds_2_mib_b1dee5ce", "Profile exceeds 2 MiB"));return data;};
        host.exportFile=[](const std::string& text){auto path=PickRuleFile(true);if(path.empty())return false;auto tmp=path;tmp+=L"."+Neurotic::Semantic::Rules::Wide(Id())+L".tmp";try{std::ofstream f(tmp,std::ios::binary|std::ios::trunc);Require(bool(f),Neurotic::UiLiteral("desktop.objectrulehost.cannot_create_export_978ba844", "Cannot create export"));f.write(text.data(),static_cast<std::streamsize>(text.size()));f.flush();Require(bool(f),Neurotic::UiLiteral("desktop.objectrulehost.cannot_write_export_abaa03e0", "Cannot write export"));f.close();Require(MoveFileExW(tmp.c_str(),path.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)!=FALSE,Neurotic::UiLiteral("desktop.objectrulehost.cannot_finish_export_e18fefbb", "Cannot finish export"));}catch(...){std::error_code ec;std::filesystem::remove(tmp,ec);throw;}return true;};
        host.globalControls=[&](){ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.objectrulehost.current_global_nr_draft_read_only_here_5201ed94", "Current global NR draft (read-only here)"));for(const auto& setting:settings)if(setting.section==Neurotic::UiLiteral("desktop.objectrulehost.dlssnr_e4e7ac7d", "DlssNr"))ImGui::TextWrapped(Neurotic::UiLiteral("desktop.objectrulehost.s_s_global_only_cee9281a", "%s: %s (global only)"),Neurotic::Translate(setting.label.c_str()).c_str(),Neurotic::Translate(setting.draft.data()).c_str());ImGui::TextWrapped(Neurotic::UiLiteral("desktop.objectrulehost.edit_global_settings_under_neural_rendering_main_998086c4", "Edit global settings under Neural Rendering > Main or Overrides. Each value uses the existing settings schema."));};
        DrawEditor(*field.ruleStore,*field.ruleEditor,host);if(revision!=field.ruleStore->Read()->revision)field.profileDraft=EncodeIni(field.ruleStore->Read()->profile);
    }catch(const std::exception& ex){field.ruleStore.reset();ImGui::TextWrapped(Neurotic::UiLiteral("desktop.objectrulehost.object_rules_s_09d282b6", "Object Rules: %s"),Neurotic::Translate(ex.what()).c_str());}
}
}
