#include <menu/Localization.h>
#include "TranslationEditorWindow.h"
#include "TranslationControlPreview.h"
#include "ui/ActionFont.h"
#include "ui/SleekWidgets.h"
#include "../../../OptiScaler/menu/localization/LanguageRuntime.h"
#include "../../../OptiScaler/menu/localization/LanguageFonts.h"
#include "../../../OptiScaler/menu/Localization.h"
#include "imgui_internal.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx11.h"
#include <d3d11.h>
#include <wrl/client.h>
#include <commdlg.h>
#include <array>
extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND,UINT,WPARAM,LPARAM);
namespace nh {
void ApplySharedTheme(bool);
using Microsoft::WRL::ComPtr;
using namespace Neurotic::Localization;
namespace {struct ContextGuard{ImGuiContext* previous=ImGui::GetCurrentContext();ContextGuard(ImGuiContext* next){ImGui::SetCurrentContext(next);}~ContextGuard(){ImGui::SetCurrentContext(previous);}};
void CheckEditor(HRESULT result){if(FAILED(result))throw std::runtime_error(Neurotic::UiMessage("desktop.translationeditorwindow.translation_editor_presentation_resources_are_un_a9b152c9", "Translation Editor presentation resources are unavailable."));}}
std::filesystem::path ChooseLanguageFile(HWND owner,bool save,const wchar_t* suggested){wchar_t path[32768]{};if(save)wcsncpy_s(path,suggested,_TRUNCATE);OPENFILENAMEW dialog{sizeof(dialog)};dialog.hwndOwner=owner;auto filter=nh::Wide(Neurotic::UiMessage("desktop.translationeditorwindow.neurotic_language_nrlang_5815a155", "NeuRotic language (*.nrlang)"));filter.push_back(0);filter+=L"*.nrlang";filter.push_back(0);filter+=nh::Wide(Neurotic::UiMessage("desktop.native.24c1f3149f33", "JSON (*.json)"));filter.push_back(0);filter+=L"*.json";filter.push_back(0);filter.push_back(0);dialog.lpstrFilter=filter.c_str();dialog.lpstrFile=path;dialog.nMaxFile=32768;dialog.lpstrDefExt=L"nrlang";dialog.Flags=OFN_NOCHANGEDIR|OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);return (save?GetSaveFileNameW(&dialog):GetOpenFileNameW(&dialog))?std::filesystem::path(path):std::filesystem::path{};}
struct TranslationEditorWindow::Impl {
 HWND owner=nullptr,window=nullptr;ImGuiContext* gui=nullptr;LanguageStore& store;ComPtr<ID3D11Device> device;ComPtr<ID3D11DeviceContext> context;ComPtr<IDXGISwapChain> chain;ComPtr<ID3D11RenderTargetView> target;
 TranslationEditorModel model;std::string packId,status,locale,lastLocale,selected;std::array<char,32769> text{};std::array<char,256> search{},author{},name{},version{};int filter=0,surface=0;bool previewLight=false,compact=false;float previewScale=1,dpi=0;bool light=false;UINT width=0,height=0;bool closePending=false,conflict=false;ImGuiID openerWindow=0,openerItem=0;
 Impl(HWND parent,ID3D11Device* dev,ID3D11DeviceContext* dc,LanguageStore& source):owner(parent),store(source),device(dev),context(dc){}
 static LRESULT CALLBACK Proc(HWND hwnd,UINT msg,WPARAM w,LPARAM l){auto* self=reinterpret_cast<Impl*>(GetWindowLongPtrW(hwnd,GWLP_USERDATA));if(msg==WM_NCCREATE){self=static_cast<Impl*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams);SetWindowLongPtrW(hwnd,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));}if(!self)return DefWindowProcW(hwnd,msg,w,l);ContextGuard guard(self->gui);
  if(msg==WM_CLOSE){self->model.RequestClose();return 0;}if(msg==WM_SIZE){if(w!=SIZE_MINIMIZED){self->width=LOWORD(l);self->height=HIWORD(l);}return 0;}
  if(msg==WM_GETMINMAXINFO){auto* info=reinterpret_cast<MINMAXINFO*>(l);info->ptMinTrackSize={640,520};return 0;}
  if(msg==WM_DPICHANGED){auto* rect=reinterpret_cast<RECT*>(l);SetWindowPos(hwnd,nullptr,rect->left,rect->top,rect->right-rect->left,rect->bottom-rect->top,SWP_NOZORDER|SWP_NOACTIVATE);return 0;}
  if(self->gui&&ImGui_ImplWin32_WndProcHandler(hwnd,msg,w,l))return 1;return DefWindowProcW(hwnd,msg,w,l);
 }
 void Target(){ComPtr<ID3D11Texture2D> texture;CheckEditor(chain->GetBuffer(0,IID_PPV_ARGS(&texture)));CheckEditor(device->CreateRenderTargetView(texture.Get(),nullptr,&target));}
 void Fonts(){auto& io=ImGui::GetIO();io.Fonts->Clear();wchar_t windows[MAX_PATH]{};GetWindowsDirectoryW(windows,MAX_PATH);auto path=std::filesystem::path(windows)/L"Fonts/segoeui.ttf";if(!io.Fonts->AddFontFromFileTTF(path.string().c_str(),18))io.Fonts->AddFontDefault();AddFontFallbacks(io.Fonts,18,SelectedLocale());ui::AddActionFont(io.Fonts,18);AddFontFallbacks(io.Fonts,18,SelectedLocale());lastLocale=SelectedLocale();if(window)SetWindowTextW(window,nh::Wide(Neurotic::UiMessage("desktop.translationeditorwindow.translation_editor_neurotic_ca8788b2", "Translation Editor — NeuRotic")).c_str());}
 void Create(){if(GImGui&&GImGui->NavWindow){openerWindow=GImGui->NavWindow->ID;openerItem=GImGui->NavId;}WNDCLASSEXW wc{sizeof(wc)};wc.lpfnWndProc=Proc;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"NeuRoticTranslationEditor";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);RegisterClassExW(&wc);
  MONITORINFO monitor{sizeof(monitor)};GetMonitorInfoW(MonitorFromWindow(owner,MONITOR_DEFAULTTONEAREST),&monitor);int editorWidth=std::min(1120,int(monitor.rcWork.right-monitor.rcWork.left)),editorHeight=std::min(960,int(monitor.rcWork.bottom-monitor.rcWork.top));
  window=CreateWindowExW(0,wc.lpszClassName,nh::Wide(Neurotic::UiMessage("desktop.translationeditorwindow.translation_editor_neurotic_ca8788b2", "Translation Editor — NeuRotic")).c_str(),WS_OVERLAPPEDWINDOW,monitor.rcWork.left+(monitor.rcWork.right-monitor.rcWork.left-editorWidth)/2,monitor.rcWork.top+(monitor.rcWork.bottom-monitor.rcWork.top-editorHeight)/2,editorWidth,editorHeight,owner,nullptr,wc.hInstance,this);if(!window)throw std::runtime_error(Neurotic::UiMessage("desktop.translationeditorwindow.translation_editor_could_not_be_opened_e7c550f1", "Translation Editor could not be opened."));
  ComPtr<IDXGIDevice> dxgi;ComPtr<IDXGIAdapter> adapter;ComPtr<IDXGIFactory> factory;CheckEditor(device.As(&dxgi));CheckEditor(dxgi->GetAdapter(&adapter));CheckEditor(adapter->GetParent(IID_PPV_ARGS(&factory)));DXGI_SWAP_CHAIN_DESC desc{};desc.BufferCount=2;desc.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;desc.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;desc.OutputWindow=window;desc.SampleDesc.Count=1;desc.Windowed=true;desc.SwapEffect=DXGI_SWAP_EFFECT_DISCARD;CheckEditor(factory->CreateSwapChain(device.Get(),&desc,&chain));Target();
  auto* previous=ImGui::GetCurrentContext();struct RestoreContext{ImGuiContext* context;~RestoreContext(){ImGui::SetCurrentContext(context);}} restore{previous};gui=ImGui::CreateContext();ImGui::SetCurrentContext(gui);ImGui::GetIO().ConfigFlags|=ImGuiConfigFlags_NavEnableKeyboard;ImGui::GetIO().IniFilename=nullptr;Fonts();if(!ImGui_ImplWin32_Init(window)||!ImGui_ImplDX11_Init(device.Get(),context.Get()))throw std::runtime_error(Neurotic::UiMessage("desktop.translationeditorwindow.translation_editor_ui_initialization_failed_8f2161ed", "Translation Editor UI initialization failed."));ShowWindow(window,SW_SHOW);SetForegroundWindow(window);
 }
 void Close(){if(!window&&!gui)return;auto* previous=ImGui::GetCurrentContext();if(gui){ImGui::SetCurrentContext(gui);ImGui_ImplDX11_Shutdown();ImGui_ImplWin32_Shutdown();ImGui::DestroyContext(gui);gui=nullptr;}ImGui::SetCurrentContext(previous);context->OMSetRenderTargets(0,nullptr,nullptr);target.Reset();chain.Reset();if(window)DestroyWindow(window);window=nullptr;if(IsWindow(owner)){SetForegroundWindow(owner);SetFocus(owner);}if(previous&&openerWindow){if(auto* pane=ImGui::FindWindowByID(openerWindow)){ImGui::FocusWindow(pane);if(openerItem)ImGui::SetFocusID(openerItem,pane);}}}
 bool Save(){auto result=store.SaveDraft(packId,model.Document());status=result.message;if(result.success)model.MarkSaved();return result.success;}
 void Load(std::string_view id){packId=id;model.Load(store.ReadDraft(id));locale=model.Document().value("locale",std::string{});strncpy_s(author.data(),author.size(),model.Document().value(Neurotic::UiLiteral("desktop.languagemanagerview.author_10f28704", "author"),std::string{}).c_str(),_TRUNCATE);strncpy_s(name.data(),name.size(),model.Document().value(Neurotic::UiLiteral("desktop.translationeditorwindow.name_ef8e2b72", "name"),std::string{}).c_str(),_TRUNCATE);strncpy_s(version.data(),version.size(),model.Document().value(Neurotic::UiLiteral("desktop.translationeditorwindow.version_523b0a16", "version"),std::string{}).c_str(),_TRUNCATE);selected.clear();search.fill(0);filter=surface=0;status.clear();}
 void Draw(){ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(ImGui::GetIO().DisplaySize);ImGui::Begin("TranslationEditorSurface",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoMove|ImGuiWindowFlags_NoSavedSettings);float scale=dpi>0?dpi:GetDpiForWindow(window)/96.f;auto nextAction=[&](const char* label){const float right=ImGui::GetCursorScreenPos().x+ImGui::GetContentRegionAvail().x;const float width=ImGui::CalcTextSize(Neurotic::Translate(label).c_str(),nullptr,true).x+ImGui::GetStyle().FramePadding.x*2;if(ImGui::GetItemRectMax().x+ImGui::GetStyle().ItemSpacing.x+width<=right)ImGui::SameLine();};
  ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.languagemanagerview.translation_editor_79e1b38f", "Translation Editor"));ImGui::SameLine();ImGui::TextDisabled("%s · %s",Neurotic::Translate(locale.c_str()).c_str(),name.data());
  if(ui::Button(Neurotic::UiLiteral("desktop.translationeditorwindow.save_draft_bb95cbc4", "Save Draft")))Save();nextAction(Neurotic::UiLiteral("desktop.translationeditorwindow.apply_86764cbe", "Apply"));if(ui::Button(Neurotic::UiLiteral("desktop.translationeditorwindow.apply_86764cbe", "Apply"))){auto result=store.Apply(packId,model.Document());status=result.message;if(result.success)QueueSharedCatalog(store.ActivePack());}nextAction(Neurotic::UiLiteral("desktop.languagemanagerview.import_833627da", "Import"));if(ui::Button(Neurotic::UiLiteral("desktop.languagemanagerview.import_833627da", "Import"))){auto path=ChooseLanguageFile(window,false);if(!path.empty()){auto result=store.ImportPack(path);status=result.message;if(result.success&&result.packId==packId&&!model.Dirty())Load(packId);}}
  nextAction(Neurotic::UiLiteral("desktop.translationeditorwindow.export_7de92eaf", "Export"));if(ui::Button(Neurotic::UiLiteral("desktop.translationeditorwindow.export_7de92eaf", "Export"))){auto path=ChooseLanguageFile(window,true);if(!path.empty()&&Save()){auto result=store.ExportPack(packId,path);status=result.message;}}nextAction(Neurotic::UiLiteral("desktop.hubshell.close_4bae39a9", "Close"));if(ui::Button(Neurotic::UiLiteral("desktop.hubshell.close_4bae39a9", "Close")))model.RequestClose();
  ImGui::TextWrapped(Neurotic::UiLiteral("desktop.translationeditorwindow.save_draft_keeps_edits_without_changing_the_inte_22fd0f9a", "Save Draft keeps edits inactive. Apply updates the App and next in-game launch."));
  if(ImGui::BeginTable("##Metadata",ImGui::GetContentRegionAvail().x>420*scale?3:1)){ImGui::TableNextColumn();ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.languagemanagerview.name_f51763bb", "Name"));ImGui::SetNextItemWidth(-1);if(ImGui::InputText("##Name",name.data(),name.size()))model.Metadata()[Neurotic::UiLiteral("desktop.translationeditorwindow.name_ef8e2b72", "name")]=name.data();ImGui::TableNextColumn();ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.translationeditorwindow.author_f09ad955", "Author"));ImGui::SetNextItemWidth(-1);if(ImGui::InputText("##Author",author.data(),author.size()))model.Metadata()[Neurotic::UiLiteral("desktop.languagemanagerview.author_10f28704", "author")]=author.data();ImGui::TableNextColumn();ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.translationeditorwindow.version_3a042c6c", "Version"));ImGui::SetNextItemWidth(-1);if(ImGui::InputText("##Version",version.data(),version.size()))model.Metadata()[Neurotic::UiLiteral("desktop.translationeditorwindow.version_523b0a16", "version")]=version.data();ImGui::EndTable();}
  ImGui::Separator();const float filtersWidth=ImGui::GetContentRegionAvail().x,filterGap=ImGui::GetStyle().ItemSpacing.x;
  const char* surfaceOptions=Neurotic::UiOptions("desktop.translationeditorwindow.all_surfaces_700b7e7b|desktop.translationeditorwindow.desktop_49749708|desktop.translationeditorwindow.in_game_7f0b8620|", "All surfaces\0Desktop\0In-game\0");
  const char* filterOptions=Neurotic::UiOptions("desktop.hubshell.all_d76f15bf|desktop.translationeditorwindow.missing_fdf8d84e|desktop.translationeditorwindow.needs_review_781aba29|desktop.translationeditorwindow.invalid_fe05183f|desktop.translationeditorwindow.complete_930f5793|desktop.translationeditorwindow.obsolete_292e39cc|", "All\0Missing\0Needs review\0Invalid\0Complete\0Obsolete\0");
  // UiOptions registers bindings; measure the resolved captions, not English.
  auto optionsWidth=[&](const char* options){float width=0;for(auto* option=options;*option;option+=std::char_traits<char>::length(option)+1)width=std::max(width,ImGui::CalcTextSize(Neurotic::Translate(option).c_str(),nullptr,true).x);return width+ImGui::GetFrameHeight()+ImGui::GetStyle().FramePadding.x*2;};
  const float surfaceWidth=std::min(filtersWidth,optionsWidth(surfaceOptions)),filterStatusWidth=std::min(filtersWidth,optionsWidth(filterOptions));
  const bool filtersInline=surfaceWidth+filterStatusWidth+filterGap*2+200*scale<=filtersWidth;
  ImGui::SetNextItemWidth(filtersInline?filtersWidth-surfaceWidth-filterStatusWidth-filterGap*2:filtersWidth);if(ImGui::InputTextWithHint("##Search",Neurotic::UiLiteral("desktop.translationeditorwindow.search_text_id_or_context_b17542ef", "Search text, ID, or context"),search.data(),search.size()))model.SetSearch(search.data());
  if(filtersInline)ImGui::SameLine();ImGui::SetNextItemWidth(surfaceWidth);if(ImGui::Combo("##Surface",&surface,surfaceOptions))model.SetSurface(surface);
  if(surfaceWidth+filterStatusWidth+filterGap<=filtersWidth)ImGui::SameLine();ImGui::SetNextItemWidth(filterStatusWidth);if(ImGui::Combo("##Filter",&filter,filterOptions))model.SetFilter(static_cast<EditorFilter>(filter));
  auto rows=model.Rows();ImGui::TextDisabled(Neurotic::UiLiteral("desktop.translationeditorwindow.zu_entries_s_1c993fff", "%zu entries · %s"),rows.size(),Neurotic::Translate(model.Dirty()?Neurotic::UiMessage("desktop.translationeditorwindow.unsaved_draft_d9a39913", "Unsaved draft").c_str():Neurotic::UiMessage("desktop.translationeditorwindow.draft_saved_f3e0e84e", "Draft saved").c_str()).c_str());const auto statusText=Neurotic::Translate(status.c_str());const float statusWidth=std::max(1.f,ImGui::GetContentRegionAvail().x);const float footer=std::max(ImGui::GetTextLineHeight(),ImGui::CalcTextSize(statusText.c_str(),nullptr,false,statusWidth).y)+ImGui::GetStyle().ItemSpacing.y;float listWidth=std::clamp(ImGui::GetContentRegionAvail().x*.30f,140.f,300*scale);ImGui::BeginChild(Neurotic::UiLiteral("desktop.translationeditorwindow.entries_e44ef17f", "Entries"),{listWidth,-footer},ImGuiChildFlags_Borders);ImGuiListClipper clipper;clipper.Begin(int(rows.size()));while(clipper.Step())for(int i=clipper.DisplayStart;i<clipper.DisplayEnd;++i){const auto& id=rows[i];const auto known=CanonicalEnglish().find(id);auto label=known==CanonicalEnglish().end()?id:known->second.english;ImGui::PushID(id.c_str());if(ImGui::Selectable(label.c_str(),model.Selection()==id)){model.Select(id);}if(ImGui::IsItemHovered())ImGui::SetTooltip("%s",Neurotic::Translate(id.c_str()).c_str());ImGui::PopID();}ImGui::EndChild();ImGui::SameLine();ImGui::BeginChild(Neurotic::UiLiteral("desktop.translationeditorwindow.entrydetails_41a80329", "EntryDetails"),{0,-footer},ImGuiChildFlags_Borders);
  if(!model.Selection().empty()){auto known=CanonicalEnglish().find(model.Selection());if(selected!=model.Selection()){selected=model.Selection();conflict=store.Conflicted(packId,selected);strncpy_s(text.data(),text.size(),model.Translation(selected).c_str(),_TRUNCATE);}ImGui::TextWrapped("%s",Neurotic::Translate(selected.c_str()).c_str());if(known!=CanonicalEnglish().end()){Neurotic::EnglishPreview english;ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.hubshell.english_620735a7", "English"));ImGui::TextWrapped("%s",Neurotic::Translate(known->second.english.c_str()).c_str());ImGui::TextWrapped("%s",Neurotic::Translate(known->second.context.c_str()).c_str());
    std::string tokens,terms;for(const auto& p:known->second.placeholders){if(!tokens.empty())tokens+=", ";tokens+=p.name;}for(const auto& t:known->second.preserve){if(!terms.empty())terms+=", ";terms+=t;}
    if(!tokens.empty())ImGui::TextWrapped(Neurotic::UiLiteral("desktop.languages.required_tokens","Required placeholders: %s"),Neurotic::Translate(tokens.c_str()).c_str());if(!terms.empty())ImGui::TextWrapped(Neurotic::UiLiteral("desktop.languages.required_terms","Keep these terms: %s"),Neurotic::Translate(terms.c_str()).c_str());}
   ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.translationeditorwindow.translation_a87700d6", "Translation"));if(ImGui::InputTextMultiline("##Translation",text.data(),text.size(),{-1,80*scale}))model.SetTranslation(text.data());auto error=model.Validation(selected);if(!error.empty())ImGui::TextWrapped("%s",Neurotic::Translate(error.c_str()).c_str());else ImGui::TextDisabled("%s",Neurotic::Translate(text[0]?Neurotic::UiLiteral("desktop.translationeditorwindow.usable_translation_fdd30899", "Usable translation"):Neurotic::UiLiteral("desktop.translationeditorwindow.missing_uses_the_next_available_translation_90996b7a", "Missing: uses the next available translation")).c_str());
   auto missing=MissingGlyphs(ImGui::GetFont(),ImGui::GetFontSize(),text.data());if(missing)ImGui::TextWrapped(Neurotic::UiLiteral("desktop.languages.glyph_warning","%zu characters have no glyph in the current font. Check the preview before applying this translation."),missing);
   if(conflict)ImGui::TextWrapped(Neurotic::UiLiteral("desktop.languages.local_conflict","This base entry changed after your local edit. Your edit takes precedence; review it before sharing."));
   if(!QualifiedInitialScript(locale))ImGui::TextWrapped(Neurotic::UiLiteral("desktop.translationeditorwindow.this_locale_can_be_edited_and_shared_its_script__126106c6", "This locale can be edited and shared. Its script and text direction have not been qualified in NeuRotic."));
   ImGui::Separator();ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.translationeditorwindow.control_preview_84e1f369", "Control Preview"));ui::Toggle(Neurotic::UiLiteral("desktop.translationeditorwindow.light_preview_28226883", "Light preview"),&previewLight);ImGui::SameLine();ui::Toggle(Neurotic::UiLiteral("desktop.translationeditorwindow.compact_d6853bf3", "Compact"),&compact);ImGui::SetNextItemWidth(150*scale);ImGui::SliderFloat(Neurotic::UiLiteral("desktop.translationeditorwindow.scale_8f07b209", "Scale"),&previewScale,.8f,2.f,"%.2f");
   if(known!=CanonicalEnglish().end())TranslationControlPreview(known->second,text.data(),(compact?300.f:520.f)*scale,previewLight,scale*previewScale);
  }else ImGui::TextUnformatted(Neurotic::UiLiteral("desktop.translationeditorwindow.select_an_entry_to_edit_and_preview_a9d660ed", "Select an entry to edit and preview."));ImGui::EndChild();ImGui::TextWrapped("%s",statusText.c_str());
  if(model.CloseStatus()!=CloseState::Ask&&ImGui::IsPopupOpen(Neurotic::UiLiteral("desktop.translationeditorwindow.unsaved_translation_edits_71f7b4f9", "Unsaved translation edits")))ImGui::ClosePopupToLevel(0,true);if(model.CloseStatus()==CloseState::Ask)ImGui::OpenPopup(Neurotic::UiLiteral("desktop.translationeditorwindow.unsaved_translation_edits_71f7b4f9", "Unsaved translation edits"));ImGui::SetNextWindowSizeConstraints({std::min(420.f*scale,ImGui::GetIO().DisplaySize.x-32.f*scale),0},{ImGui::GetIO().DisplaySize.x-16.f*scale,ImGui::GetIO().DisplaySize.y-16.f*scale});if(ImGui::BeginPopupModal(Neurotic::UiLiteral("desktop.translationeditorwindow.unsaved_translation_edits_71f7b4f9", "Unsaved translation edits"),nullptr,ImGuiWindowFlags_AlwaysAutoResize)){ImGui::TextWrapped(Neurotic::UiLiteral("desktop.translationeditorwindow.save_the_draft_before_closing_d930da44", "Save the draft before closing?"));if(ui::Button(Neurotic::UiLiteral("desktop.translationeditorwindow.save_draft_bb95cbc4", "Save Draft"))){if(Save()){model.DiscardClose();ImGui::CloseCurrentPopup();}}nextAction(Neurotic::UiLiteral("desktop.translationeditorwindow.discard_0de197ab", "Discard"));if(ui::Button(Neurotic::UiLiteral("desktop.translationeditorwindow.discard_0de197ab", "Discard"))){model.DiscardClose();ImGui::CloseCurrentPopup();}nextAction(Neurotic::UiLiteral("desktop.hubshell.cancel_c50f8908", "Cancel"));if(ui::Button(Neurotic::UiLiteral("desktop.hubshell.cancel_c50f8908", "Cancel"))||ImGui::IsKeyPressed(ImGuiKey_Escape)){model.CancelClose();ImGui::CloseCurrentPopup();}ImGui::EndPopup();}ImGui::End();
 }
 void Render(bool nextLight,float fixtureScale){if(!window)return;if(model.CloseStatus()==CloseState::Ready){Close();return;}ContextGuard guard(gui);if(width&&height){context->OMSetRenderTargets(0,nullptr,nullptr);target.Reset();CheckEditor(chain->ResizeBuffers(0,width,height,DXGI_FORMAT_UNKNOWN,0));width=height=0;Target();}auto newDpi=fixtureScale>0?fixtureScale:GetDpiForWindow(window)/96.f;if(dpi!=newDpi||light!=nextLight){ApplySharedTheme(nextLight);ImGui::GetStyle().ScaleAllSizes(newDpi);ImGui::GetIO().FontGlobalScale=newDpi;dpi=newDpi;light=nextLight;}
  if(lastLocale!=SelectedLocale()){Fonts();}ImGui_ImplDX11_NewFrame();ImGui_ImplWin32_NewFrame();ImGui::NewFrame();Draw();ImGui::Render();float clear[]={.07f,.09f,.12f,1};context->OMSetRenderTargets(1,target.GetAddressOf(),nullptr);context->ClearRenderTargetView(target.Get(),clear);ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());CheckEditor(chain->Present(1,0));
 }
};
TranslationEditorWindow::TranslationEditorWindow(HWND owner,ID3D11Device* device,ID3D11DeviceContext* context,LanguageStore& store):impl(std::make_unique<Impl>(owner,device,context,store)){}
TranslationEditorWindow::~TranslationEditorWindow(){impl->Close();}
bool TranslationEditorWindow::Open(std::string_view id){try{if(impl->window){if(impl->packId!=id&&impl->model.Dirty()){impl->status=Neurotic::UiMessage("desktop.translationeditorwindow.save_or_discard_the_current_draft_before_opening_87df20a2", "Save or discard the current draft before opening another language.");SetForegroundWindow(impl->window);return false;}if(impl->packId!=id)impl->Load(id);SetForegroundWindow(impl->window);return true;}impl->Load(id);impl->Create();return true;}catch(const std::exception& e){impl->status=e.what();impl->Close();return false;}}
void TranslationEditorWindow::Render(bool light,float scale){impl->Render(light,scale);}bool TranslationEditorWindow::IsOpen()const{return impl->window!=nullptr;}bool TranslationEditorWindow::RequestClose(){if(!IsOpen())return true;auto state=impl->model.RequestClose();if(state==CloseState::Ready){impl->Close();return true;}SetForegroundWindow(impl->window);return false;}
HWND TranslationEditorWindow::Handle()const{return impl->window;}TranslationEditorModel* TranslationEditorWindow::Model(){return &impl->model;}
IDXGISwapChain* TranslationEditorWindow::SwapChain()const{return impl->chain.Get();}
}
