// Generated by tools/Build-RenderingRequirements.py; edit the JSON contract.
#pragma once
namespace DlssNr::SetupRequirements {
inline constexpr unsigned Route = 2;
inline constexpr unsigned Style = 0;
inline constexpr unsigned InputSource = 0;
inline constexpr unsigned InputTransport = 0;
inline constexpr unsigned PresentInputPolicy = 2;
inline constexpr bool AllowCpuFallback = true;
}
